// `chunks` must rejoin exactly into `word`. `blank.at` is the index of the chunk
// to hide and `blank.options` are its decoys. Both decoys and `distractors` are
// hand-authored plausible misspellings — generated ones are non-words a player
// can rule out without knowing the spelling. src/game.test.js enforces all of it.
export const WORD_TIERS = [
  {
    id: 'basecamp',
    label: 'Base Camp',
    grades: 'Grades 1–2',
    description: 'First sight words and sound patterns',
    color: '#c9585f',
    icon: '⛺',
    words: [
      { word: 'said', sentence: 'She said hello to the new kid.', chunks: ['s', 'aid'], distractors: ['sed', 'sayd'], blank: { at: 1, options: ['ade', 'ayd'] } },
      { word: 'they', sentence: 'They packed snacks for the hike.', chunks: ['th', 'ey'], distractors: ['thay', 'thei'], blank: { at: 1, options: ['ay', 'ai'] } },
      { word: 'what', sentence: 'I know what to do next.', chunks: ['wh', 'at'], distractors: ['wut', 'whut'], blank: { at: 0, options: ['w', 'hw'] } },
      { word: 'come', sentence: 'Come to the campfire with us.', chunks: ['c', 'ome'], distractors: ['cum', 'kome'], blank: { at: 1, options: ['um', 'ume'] } },
      { word: 'some', sentence: 'Can I have some more paper?', chunks: ['s', 'ome'], distractors: ['sum', 'somme'], blank: { at: 1, options: ['um', 'ume'] } },
      { word: 'there', sentence: 'Look over there by the tree.', chunks: ['th', 'ere'], distractors: ['ther', 'thare'], blank: { at: 1, options: ['air', 'ear'] } },
      { word: 'where', sentence: 'Do you remember where we parked?', chunks: ['wh', 'ere'], distractors: ['wher', 'whare'], blank: { at: 1, options: ['air', 'ear'] } },
      { word: 'little', sentence: 'The little owl blinked twice.', chunks: ['lit', 'tle'], distractors: ['littel', 'litle'], blank: { at: 1, options: ['tel', 'tal'] } },
      { word: 'water', sentence: 'Please drink some water.', chunks: ['wa', 'ter'], distractors: ['watter', 'wader'], blank: { at: 1, options: ['tar', 'tor'] } },
      { word: 'after', sentence: 'We walk home after school.', chunks: ['af', 'ter'], distractors: ['affter', 'aftur'], blank: { at: 1, options: ['tar', 'tir'] } },
      { word: 'know', sentence: 'I know the way to camp.', chunks: ['kn', 'ow'], distractors: ['knoe', 'nowe'], blank: { at: 0, options: ['n', 'c'] } },
      { word: 'write', sentence: 'I write my name at the top.', chunks: ['wr', 'ite'], distractors: ['rite', 'writ'], blank: { at: 0, options: ['r', 'rh'] } },
      { word: 'many', sentence: 'How many stars can you count?', chunks: ['ma', 'ny'], distractors: ['meny', 'manny'], blank: { at: 0, options: ['me', 'mu'] } },
      { word: 'would', sentence: 'I would like a turn.', chunks: ['w', 'ould'], distractors: ['wuld', 'wold'], blank: { at: 1, options: ['uld', 'oud'] } },
      { word: 'their', sentence: 'The birds built their nest.', chunks: ['th', 'eir'], distractors: ['thier', 'thair'], blank: { at: 1, options: ['ier', 'air'] } },
      { word: 'about', sentence: 'This book is about a brave fox.', chunks: ['a', 'bout'], distractors: ['abowt', 'abot'], blank: { at: 1, options: ['bowt', 'bot'] } },
      { word: 'could', sentence: 'I could hear the rain on the roof.', chunks: ['c', 'ould'], distractors: ['cud', 'coud'], blank: { at: 1, options: ['uld', 'oud'] } },
      { word: 'should', sentence: 'We should leave soon.', chunks: ['sh', 'ould'], distractors: ['shud', 'shoud'], blank: { at: 0, options: ['sch', 'ch'] } },
      { word: 'does', sentence: 'She does her homework early.', chunks: ['d', 'oes'], distractors: ['duz', 'dose'], blank: { at: 1, options: ['uz', 'ose'] } },
      { word: 'goes', sentence: 'The bus goes past our street.', chunks: ['g', 'oes'], distractors: ['gose', 'gos'], blank: { at: 1, options: ['ose', 'os'] } },
      { word: 'very', sentence: 'The soup was very hot.', chunks: ['ver', 'y'], distractors: ['vary', 'verry'], blank: { at: 0, options: ['var', 'vur'] } },
      { word: 'from', sentence: 'I got a letter from my cousin.', chunks: ['fr', 'om'], distractors: ['form', 'frum'], blank: { at: 1, options: ['um', 'am'] } },
      { word: 'been', sentence: 'I have been to that park.', chunks: ['b', 'een'], distractors: ['ben', 'bean'], blank: { at: 1, options: ['ean', 'en'] } },
      { word: 'these', sentence: 'These apples are ripe.', chunks: ['th', 'ese'], distractors: ['thease', 'thes'], blank: { at: 1, options: ['ease', 'eze'] } },
      { word: 'those', sentence: 'Those clouds look heavy.', chunks: ['th', 'ose'], distractors: ['thoes', 'thoze'], blank: { at: 1, options: ['oes', 'oze'] } },
      { word: 'other', sentence: 'The other shoe is by the door.', chunks: ['oth', 'er'], distractors: ['othur', 'uther'], blank: { at: 1, options: ['ur', 'ar'] } },
      { word: 'under', sentence: 'The cat hid under the chair.', chunks: ['un', 'der'], distractors: ['unnder', 'undur'], blank: { at: 1, options: ['dur', 'dar'] } },
      { word: 'over', sentence: 'The bird flew over the fence.', chunks: ['o', 'ver'], distractors: ['ovur', 'overr'], blank: { at: 1, options: ['vur', 'var'] } },
      { word: 'before', sentence: 'Wash your hands before dinner.', chunks: ['be', 'fore'], distractors: ['befor', 'beefore'], blank: { at: 1, options: ['for', 'four'] } },
      { word: 'house', sentence: 'Our house has a blue door.', chunks: ['h', 'ouse'], distractors: ['hows', 'howse'], blank: { at: 1, options: ['ows', 'owse'] } },
      { word: 'mother', sentence: 'My mother reads to me at night.', chunks: ['moth', 'er'], distractors: ['muther', 'mothur'], blank: { at: 0, options: ['muth', 'mothe'] } },
      { word: 'father', sentence: 'My father packed the lunches.', chunks: ['fath', 'er'], distractors: ['fahter', 'fathur'], blank: { at: 0, options: ['fauth', 'feth'] } },
      { word: 'want', sentence: 'I want a red apple.', chunks: ['w', 'ant'], distractors: ['wont', 'wawnt'], blank: { at: 1, options: ['ont', 'unt'] } },
      { word: 'walk', sentence: 'We walk to school every day.', chunks: ['w', 'alk'], distractors: ['wok', 'wallk'], blank: { at: 1, options: ['ock', 'olk'] } },
      { word: 'talk', sentence: 'Let\'s talk about the game.', chunks: ['t', 'alk'], distractors: ['tok', 'tallk'], blank: { at: 1, options: ['ock', 'olk'] } },
      { word: 'girl', sentence: 'The girl found a shiny rock.', chunks: ['g', 'irl'], distractors: ['gril', 'gerl'], blank: { at: 1, options: ['erl', 'url'] } },
      { word: 'look', sentence: 'Take a look at this map.', chunks: ['l', 'ook'], distractors: ['luk', 'lok'], blank: { at: 1, options: ['uk', 'ouk'] } },
      { word: 'took', sentence: 'She took the last cookie.', chunks: ['t', 'ook'], distractors: ['tuk', 'tok'], blank: { at: 1, options: ['uk', 'ouk'] } },
      { word: 'good', sentence: 'That was a good try.', chunks: ['g', 'ood'], distractors: ['gud', 'goud'], blank: { at: 1, options: ['ud', 'oud'] } },
      { word: 'food', sentence: 'We packed food for the trip.', chunks: ['f', 'ood'], distractors: ['fud', 'foud'], blank: { at: 1, options: ['ud', 'oud'] } },
      { word: 'name', sentence: 'Write your name on the paper.', chunks: ['n', 'ame'], distractors: ['naim', 'nam'], blank: { at: 1, options: ['aim', 'am'] } },
      { word: 'game', sentence: 'The game starts at noon.', chunks: ['g', 'ame'], distractors: ['gaim', 'gam'], blank: { at: 1, options: ['aim', 'am'] } },
      { word: 'made', sentence: 'I made a card for you.', chunks: ['m', 'ade'], distractors: ['maid', 'mad'], blank: { at: 1, options: ['aid', 'ad'] } },
      { word: 'take', sentence: 'Please take a seat.', chunks: ['t', 'ake'], distractors: ['taik', 'tak'], blank: { at: 1, options: ['aik', 'ak'] } },
      { word: 'make', sentence: 'Let\'s make a plan.', chunks: ['m', 'ake'], distractors: ['maik', 'mak'], blank: { at: 1, options: ['aik', 'ak'] } },
      { word: 'home', sentence: 'We walked home in the rain.', chunks: ['h', 'ome'], distractors: ['hoem', 'hom'], blank: { at: 1, options: ['oem', 'om'] } },
      { word: 'time', sentence: 'It is time for lunch.', chunks: ['t', 'ime'], distractors: ['tiem', 'tym'], blank: { at: 1, options: ['iem', 'ym'] } },
      { word: 'like', sentence: 'I like reading before bed.', chunks: ['l', 'ike'], distractors: ['lik', 'lyke'], blank: { at: 1, options: ['ik', 'yke'] } },
      { word: 'ride', sentence: 'We ride bikes on Saturday.', chunks: ['r', 'ide'], distractors: ['ryde', 'rid'], blank: { at: 1, options: ['yde', 'id'] } },
      { word: 'side', sentence: 'Sit on this side of the bus.', chunks: ['s', 'ide'], distractors: ['syde', 'sid'], blank: { at: 1, options: ['yde', 'id'] } },
      { word: 'ball', sentence: 'Throw the ball to me.', chunks: ['b', 'all'], distractors: ['bal', 'baul'], blank: { at: 1, options: ['al', 'aul'] } },
      { word: 'call', sentence: 'I will call you after dinner.', chunks: ['c', 'all'], distractors: ['cal', 'caul'], blank: { at: 0, options: ['k', 'ck'] } },
      { word: 'tall', sentence: 'The tall tree lost its leaves.', chunks: ['t', 'all'], distractors: ['tal', 'taul'], blank: { at: 1, options: ['al', 'aul'] } },
      { word: 'wall', sentence: 'The clock hangs on the wall.', chunks: ['w', 'all'], distractors: ['wal', 'waul'], blank: { at: 1, options: ['al', 'aul'] } },
      { word: 'fall', sentence: 'Leaves fall in October.', chunks: ['f', 'all'], distractors: ['fal', 'faul'], blank: { at: 1, options: ['al', 'aul'] } },
      { word: 'cold', sentence: 'The soup got cold fast.', chunks: ['c', 'old'], distractors: ['cald', 'coald'], blank: { at: 0, options: ['k', 'ch'] } },
      { word: 'hold', sentence: 'Please hold my hand.', chunks: ['h', 'old'], distractors: ['hald', 'hoald'], blank: { at: 1, options: ['ald', 'oald'] } },
      { word: 'told', sentence: 'She told a funny joke.', chunks: ['t', 'old'], distractors: ['tald', 'toald'], blank: { at: 1, options: ['ald', 'oald'] } },
      { word: 'find', sentence: 'Can you find my shoe?', chunks: ['f', 'ind'], distractors: ['fynd', 'fined'], blank: { at: 1, options: ['ynd', 'end'] } },
      { word: 'jump', sentence: 'The frog can jump far.', chunks: ['j', 'ump'], distractors: ['jumb', 'jup'], blank: { at: 0, options: ['g', 'dg'] } },
      { word: 'help', sentence: 'Can you help me carry this?', chunks: ['h', 'elp'], distractors: ['hep', 'healp'], blank: { at: 1, options: ['ellp', 'elep'] } },
      { word: 'best', sentence: 'That was the best day ever.', chunks: ['b', 'est'], distractors: ['bes', 'beast'], blank: { at: 1, options: ['este', 'esst'] } },
      { word: 'next', sentence: 'Turn to the next page.', chunks: ['n', 'ext'], distractors: ['nekst', 'nex'], blank: { at: 1, options: ['ekst', 'ekt'] } },
      { word: 'back', sentence: 'Put the book back on the shelf.', chunks: ['b', 'ack'], distractors: ['bak', 'baack'], blank: { at: 1, options: ['ak', 'ock'] } },
    ],
  },
  {
    id: 'warmup',
    label: 'Warm-up Woods',
    grades: 'Grades 2–3',
    description: 'Common words and friendly patterns',
    color: '#56a87f',
    icon: '🌲',
    words: [
      { word: 'because', sentence: 'I wore boots because it was raining.', chunks: ['be', 'cause'], distractors: ['becuase', 'becaus'], blank: { at: 1, options: ['cuase', 'caus'] } },
      { word: 'friend', sentence: 'My friend saved me a seat.', chunks: ['fri', 'end'], distractors: ['freind', 'frend'], blank: { at: 0, options: ['fre', 'fir'] } },
      { word: 'people', sentence: 'Many people came to the game.', chunks: ['peo', 'ple'], distractors: ['peeple', 'pepole'], blank: { at: 0, options: ['pea', 'pio'] } },
      { word: 'every', sentence: 'We read together every night.', chunks: ['ev', 'er', 'y'], distractors: ['evry', 'everey'], blank: { at: 1, options: ['ir', 'ur'] } },
      { word: 'school', sentence: 'The school library has new books.', chunks: ['sch', 'ool'], distractors: ['scool', 'schole'], blank: { at: 0, options: ['sc', 'sk'] } },
      { word: 'again', sentence: 'Please play that song again.', chunks: ['a', 'gain'], distractors: ['agen', 'agian'], blank: { at: 1, options: ['gian', 'gan'] } },
      { word: 'answer', sentence: 'I knew the answer to the riddle.', chunks: ['an', 'swer'], distractors: ['anser', 'answere'], blank: { at: 1, options: ['ser', 'sur'] } },
      { word: 'thought', sentence: 'I thought about the puzzle.', chunks: ['th', 'ought'], distractors: ['thot', 'thoughte'], blank: { at: 1, options: ['ot', 'aught'] } },
      { word: 'through', sentence: 'We hiked through the woods.', chunks: ['thr', 'ough'], distractors: ['thru', 'throught'], blank: { at: 1, options: ['ugh', 'ou'] } },
      { word: 'money', sentence: 'I saved money for a new book.', chunks: ['mon', 'ey'], distractors: ['mony', 'munny'], blank: { at: 1, options: ['y', 'ie'] } },
      { word: 'together', sentence: 'Let us read together tonight.', chunks: ['to', 'geth', 'er'], distractors: ['togather', 'togeather'], blank: { at: 1, options: ['gath', 'geath'] } },
      { word: 'morning', sentence: 'The morning air felt cool.', chunks: ['morn', 'ing'], distractors: ['moring', 'mornning'], blank: { at: 0, options: ['mourn', 'morne'] } },
      { word: 'children', sentence: 'The children lined up quietly.', chunks: ['chil', 'dren'], distractors: ['childern', 'childran'], blank: { at: 1, options: ['dern', 'dran'] } },
      { word: 'family', sentence: 'My family eats dinner at six.', chunks: ['fam', 'i', 'ly'], distractors: ['familly', 'famly'], blank: { at: 1, options: ['e', 'a'] } },
      { word: 'birthday', sentence: 'Her birthday is in October.', chunks: ['birth', 'day'], distractors: ['brithday', 'birhtday'], blank: { at: 0, options: ['berth', 'burth'] } },
      { word: 'always', sentence: 'He always ties his shoes first.', chunks: ['al', 'ways'], distractors: ['allways', 'alwayz'], blank: { at: 0, options: ['all', 'ol'] } },
      { word: 'another', sentence: 'Can I have another turn?', chunks: ['an', 'oth', 'er'], distractors: ['anouther', 'annother'], blank: { at: 1, options: ['uth', 'ath'] } },
      { word: 'something', sentence: 'I heard something outside.', chunks: ['some', 'thing'], distractors: ['somthing', 'someting'], blank: { at: 0, options: ['sum', 'som'] } },
      { word: 'anything', sentence: 'You can build anything with blocks.', chunks: ['any', 'thing'], distractors: ['enything', 'anithing'], blank: { at: 0, options: ['eny', 'ani'] } },
      { word: 'around', sentence: 'We walked around the pond.', chunks: ['a', 'round'], distractors: ['arownd', 'aroud'], blank: { at: 1, options: ['rownd', 'roud'] } },
      { word: 'between', sentence: 'Sit between your two classmates.', chunks: ['be', 'tween'], distractors: ['betwen', 'betwean'], blank: { at: 1, options: ['twen', 'twean'] } },
      { word: 'brother', sentence: 'My brother lost a tooth.', chunks: ['broth', 'er'], distractors: ['bruther', 'brothur'], blank: { at: 0, options: ['bruth', 'brothe'] } },
      { word: 'sister', sentence: 'My sister plays the flute.', chunks: ['sis', 'ter'], distractors: ['sistur', 'sistter'], blank: { at: 1, options: ['tur', 'tar'] } },
      { word: 'teacher', sentence: 'Our teacher read us a poem.', chunks: ['teach', 'er'], distractors: ['teecher', 'techer'], blank: { at: 0, options: ['teech', 'tech'] } },
      { word: 'picture', sentence: 'She drew a picture of the lake.', chunks: ['pic', 'ture'], distractors: ['pitcher', 'picure'], blank: { at: 1, options: ['cher', 'chure'] } },
      { word: 'number', sentence: 'Write your lucky number here.', chunks: ['num', 'ber'], distractors: ['numbur', 'nummber'], blank: { at: 1, options: ['bur', 'bar'] } },
      { word: 'finally', sentence: 'We finally reached the top.', chunks: ['fi', 'nal', 'ly'], distractors: ['finaly', 'finelly'], blank: { at: 1, options: ['nel', 'nall'] } },
      { word: 'really', sentence: 'That was really close.', chunks: ['re', 'al', 'ly'], distractors: ['realy', 'reallly'], blank: { at: 2, options: ['y', 'lly'] } },
      { word: 'person', sentence: 'Only one person can go first.', chunks: ['per', 'son'], distractors: ['persen', 'purson'], blank: { at: 0, options: ['pur', 'par'] } },
      { word: 'window', sentence: 'Rain tapped on the window.', chunks: ['win', 'dow'], distractors: ['windo', 'winddow'], blank: { at: 1, options: ['doe', 'dou'] } },
      { word: 'summer', sentence: 'We swim all summer long.', chunks: ['sum', 'mer'], distractors: ['sumer', 'summur'], blank: { at: 1, options: ['mur', 'mar'] } },
      { word: 'winter', sentence: 'The winter wind was sharp.', chunks: ['win', 'ter'], distractors: ['wintur', 'winnter'], blank: { at: 1, options: ['tur', 'tar'] } },
      { word: 'jacket', sentence: 'She zipped up her jacket.', chunks: ['jack', 'et'], distractors: ['jaket', 'jackit'], blank: { at: 1, options: ['it', 'ett'] } },
      { word: 'pocket', sentence: 'He found a coin in his pocket.', chunks: ['pock', 'et'], distractors: ['poket', 'pockit'], blank: { at: 1, options: ['it', 'ett'] } },
      { word: 'rabbit', sentence: 'The rabbit hopped across the lawn.', chunks: ['rab', 'bit'], distractors: ['rabit', 'rabbet'], blank: { at: 0, options: ['rob', 'rub'] } },
      { word: 'basket', sentence: 'We packed a picnic basket.', chunks: ['bas', 'ket'], distractors: ['baskit', 'bascket'], blank: { at: 1, options: ['kit', 'cket'] } },
      { word: 'garden', sentence: 'We planted carrots in the garden.', chunks: ['gar', 'den'], distractors: ['gardin', 'gardan'], blank: { at: 1, options: ['din', 'dan'] } },
      { word: 'kitten', sentence: 'The kitten chased a leaf.', chunks: ['kit', 'ten'], distractors: ['kiten', 'kittin'], blank: { at: 1, options: ['tin', 'ton'] } },
      { word: 'purple', sentence: 'She painted the fence purple.', chunks: ['pur', 'ple'], distractors: ['purpel', 'perple'], blank: { at: 1, options: ['pel', 'pal'] } },
      { word: 'yellow', sentence: 'The bus is bright yellow.', chunks: ['yel', 'low'], distractors: ['yello', 'yelow'], blank: { at: 1, options: ['lo', 'loe'] } },
      { word: 'orange', sentence: 'I peeled an orange for lunch.', chunks: ['or', 'ange'], distractors: ['ornge', 'orang'], blank: { at: 1, options: ['ang', 'anje'] } },
      { word: 'circle', sentence: 'Draw a circle around your answer.', chunks: ['cir', 'cle'], distractors: ['sircle', 'circel'], blank: { at: 0, options: ['sir', 'cer'] } },
      { word: 'bottle', sentence: 'Fill the bottle with water.', chunks: ['bot', 'tle'], distractors: ['botle', 'bottel'], blank: { at: 1, options: ['tel', 'tal'] } },
      { word: 'candle', sentence: 'She lit a candle at dusk.', chunks: ['can', 'dle'], distractors: ['candel', 'candl'], blank: { at: 1, options: ['del', 'dal'] } },
      { word: 'puzzle', sentence: 'We finished the puzzle together.', chunks: ['puz', 'zle'], distractors: ['puzle', 'puzzel'], blank: { at: 1, options: ['zel', 'zal'] } },
      { word: 'turtle', sentence: 'The turtle swam to the rock.', chunks: ['tur', 'tle'], distractors: ['turtel', 'turtal'], blank: { at: 1, options: ['tel', 'tal'] } },
      { word: 'eagle', sentence: 'An eagle soared above the cliff.', chunks: ['ea', 'gle'], distractors: ['eagel', 'eegle'], blank: { at: 1, options: ['gel', 'gal'] } },
      { word: 'apple', sentence: 'I packed an apple for snack.', chunks: ['ap', 'ple'], distractors: ['appel', 'appal'], blank: { at: 1, options: ['pel', 'pal'] } },
      { word: 'pencil', sentence: 'My pencil needs sharpening.', chunks: ['pen', 'cil'], distractors: ['pensil', 'pencal'], blank: { at: 1, options: ['sil', 'cal'] } },
      { word: 'dinner', sentence: 'We ate dinner at six.', chunks: ['din', 'ner'], distractors: ['diner', 'dinnar'], blank: { at: 1, options: ['nar', 'nur'] } },
      { word: 'supper', sentence: 'Supper was ready at seven.', chunks: ['sup', 'per'], distractors: ['suppar', 'supor'], blank: { at: 1, options: ['par', 'pur'] } },
      { word: 'napkin', sentence: 'Wipe your hands on a napkin.', chunks: ['nap', 'kin'], distractors: ['napkan', 'napken'], blank: { at: 1, options: ['kan', 'ken'] } },
      { word: 'blanket', sentence: 'She wrapped up in a warm blanket.', chunks: ['blan', 'ket'], distractors: ['blankit', 'blancket'], blank: { at: 1, options: ['kit', 'cket'] } },
      { word: 'mitten', sentence: 'He lost one mitten in the snow.', chunks: ['mit', 'ten'], distractors: ['miten', 'mittin'], blank: { at: 1, options: ['tin', 'ton'] } },
      { word: 'ladder', sentence: 'Climb the ladder carefully.', chunks: ['lad', 'der'], distractors: ['ladar', 'laddar'], blank: { at: 1, options: ['dar', 'dur'] } },
      { word: 'hammer', sentence: 'Dad used a hammer to fix the shelf.', chunks: ['ham', 'mer'], distractors: ['hamer', 'hammar'], blank: { at: 1, options: ['mar', 'mur'] } },
      { word: 'spider', sentence: 'A spider spun a web by the door.', chunks: ['spi', 'der'], distractors: ['spidar', 'spyder'], blank: { at: 1, options: ['dar', 'dur'] } },
      { word: 'tiger', sentence: 'The tiger paced in the shade.', chunks: ['ti', 'ger'], distractors: ['tigar', 'tyger'], blank: { at: 1, options: ['gar', 'gur'] } },
      { word: 'dragon', sentence: 'The story had a friendly dragon.', chunks: ['dra', 'gon'], distractors: ['dragen', 'dragan'], blank: { at: 1, options: ['gen', 'gan'] } },
      { word: 'wagon', sentence: 'We pulled the wagon up the hill.', chunks: ['wag', 'on'], distractors: ['wagen', 'waggon'], blank: { at: 1, options: ['en', 'an'] } },
      { word: 'cabin', sentence: 'We stayed in a cozy cabin.', chunks: ['cab', 'in'], distractors: ['cabbin', 'caben'], blank: { at: 0, options: ['cob', 'cub'] } },
      { word: 'cactus', sentence: 'The cactus sat on the windowsill.', chunks: ['cac', 'tus'], distractors: ['cactis', 'kactus'], blank: { at: 1, options: ['tis', 'tuss'] } },
      { word: 'muffin', sentence: 'She baked a blueberry muffin.', chunks: ['muf', 'fin'], distractors: ['mufin', 'muffen'], blank: { at: 1, options: ['fen', 'fan'] } },
      { word: 'tunnel', sentence: 'The train went through the tunnel.', chunks: ['tun', 'nel'], distractors: ['tunel', 'tunnal'], blank: { at: 1, options: ['nal', 'nul'] } },
    ],
  },
  {
    id: 'explorer',
    label: 'Explorer Creek',
    grades: 'Grades 3–4',
    description: 'Vowels, endings, and longer words',
    color: '#428fa4',
    icon: '🛶',
    words: [
      { word: 'different', sentence: 'Each snowflake looks different.', chunks: ['dif', 'fer', 'ent'], distractors: ['diffrent', 'differant'], blank: { at: 1, options: ['fr', 'far'] } },
      { word: 'important', sentence: 'Practice is important when learning.', chunks: ['im', 'por', 'tant'], distractors: ['importent', 'inportant'], blank: { at: 2, options: ['tent', 'tint'] } },
      { word: 'favorite', sentence: 'Blue is my favorite color.', chunks: ['fa', 'vor', 'ite'], distractors: ['faverite', 'favorit'], blank: { at: 1, options: ['ver', 'vour'] } },
      { word: 'beautiful', sentence: 'The sunset was beautiful.', chunks: ['beau', 'ti', 'ful'], distractors: ['beautifull', 'butiful'], blank: { at: 0, options: ['bue', 'bu'] } },
      { word: 'probably', sentence: 'We will probably leave after lunch.', chunks: ['prob', 'a', 'bly'], distractors: ['probly', 'probabaly'], blank: { at: 2, options: ['ble', 'bley'] } },
      { word: 'remember', sentence: 'Remember to bring your jacket.', chunks: ['re', 'mem', 'ber'], distractors: ['remeber', 'remmember'], blank: { at: 1, options: ['mm', 'men'] } },
      { word: 'surprise', sentence: 'The party was a surprise.', chunks: ['sur', 'prise'], distractors: ['suprise', 'surprize'], blank: { at: 0, options: ['su', 'ser'] } },
      { word: 'calendar', sentence: 'Mark the date on the calendar.', chunks: ['cal', 'en', 'dar'], distractors: ['calender', 'calandar'], blank: { at: 2, options: ['der', 'dor'] } },
      { word: 'neighbor', sentence: 'Our neighbor has a bright red door.', chunks: ['neigh', 'bor'], distractors: ['nieghbor', 'naybor'], blank: { at: 0, options: ['nigh', 'neig'] } },
      { word: 'question', sentence: 'I raised my hand to ask a question.', chunks: ['ques', 'tion'], distractors: ['queston', 'questoin'], blank: { at: 1, options: ['shun', 'sion'] } },
      { word: 'straight', sentence: 'Draw a straight line down the page.', chunks: ['str', 'aight'], distractors: ['strait', 'strate'], blank: { at: 1, options: ['ait', 'aght'] } },
      { word: 'believe', sentence: 'I believe you can do this.', chunks: ['be', 'lieve'], distractors: ['beleive', 'beleve'], blank: { at: 1, options: ['leive', 'leave'] } },
      { word: 'february', sentence: 'February is the shortest month.', chunks: ['feb', 'ru', 'ary'], distractors: ['febuary', 'februrary'], blank: { at: 1, options: ['u', 'ra'] } },
      { word: 'exercise', sentence: 'We exercise before the game starts.', chunks: ['ex', 'er', 'cise'], distractors: ['excercise', 'exersize'], blank: { at: 2, options: ['size', 'sise'] } },
      { word: 'treasure', sentence: 'The map led us to buried treasure.', chunks: ['trea', 'sure'], distractors: ['treshure', 'treasre'], blank: { at: 0, options: ['tre', 'trae'] } },
      { word: 'wonderful', sentence: 'That was a wonderful story.', chunks: ['won', 'der', 'ful'], distractors: ['wonderfull', 'wunderful'], blank: { at: 2, options: ['full', 'fal'] } },
      { word: 'dangerous', sentence: 'That cliff looks dangerous.', chunks: ['dan', 'ger', 'ous'], distractors: ['dangerus', 'daingerous'], blank: { at: 2, options: ['us', 'ious'] } },
      { word: 'delicious', sentence: 'The soup smelled delicious.', chunks: ['de', 'li', 'cious'], distractors: ['delicous', 'dilicious'], blank: { at: 2, options: ['shus', 'tious'] } },
      { word: 'describe', sentence: 'Can you describe the bird?', chunks: ['de', 'scribe'], distractors: ['discribe', 'describ'], blank: { at: 0, options: ['di', 'da'] } },
      { word: 'imagine', sentence: 'Imagine a city under the sea.', chunks: ['i', 'mag', 'ine'], distractors: ['immagine', 'imagin'], blank: { at: 1, options: ['meg', 'mig'] } },
      { word: 'machine', sentence: 'The machine hummed softly.', chunks: ['ma', 'chine'], distractors: ['mashine', 'machin'], blank: { at: 1, options: ['shine', 'chin'] } },
      { word: 'minute', sentence: 'Wait one minute, please.', chunks: ['min', 'ute'], distractors: ['minit', 'minutte'], blank: { at: 1, options: ['it', 'oot'] } },
      { word: 'natural', sentence: 'The cave is a natural shelter.', chunks: ['nat', 'u', 'ral'], distractors: ['naturel', 'nattural'], blank: { at: 2, options: ['rel', 'rul'] } },
      { word: 'ocean', sentence: 'The ocean was calm today.', chunks: ['o', 'cean'], distractors: ['ocian', 'oshean'], blank: { at: 1, options: ['shun', 'cian'] } },
      { word: 'often', sentence: 'We often hike on Sundays.', chunks: ['of', 'ten'], distractors: ['offen', 'oftin'], blank: { at: 1, options: ['tin', 'tan'] } },
      { word: 'quiet', sentence: 'The reading room stayed quiet.', chunks: ['qui', 'et'], distractors: ['quite', 'quiat'], blank: { at: 0, options: ['que', 'qwi'] } },
      { word: 'special', sentence: 'Today is a special day.', chunks: ['spe', 'cial'], distractors: ['speshal', 'specail'], blank: { at: 1, options: ['shal', 'tial'] } },
      { word: 'stomach', sentence: 'My stomach growled loudly.', chunks: ['stom', 'ach'], distractors: ['stomache', 'stumach'], blank: { at: 1, options: ['ack', 'atch'] } },
      { word: 'terrible', sentence: 'That was a terrible storm.', chunks: ['ter', 'ri', 'ble'], distractors: ['terrable', 'terible'], blank: { at: 1, options: ['ra', 're'] } },
      { word: 'tomorrow', sentence: 'We leave tomorrow at dawn.', chunks: ['to', 'mor', 'row'], distractors: ['tommorow', 'tomorow'], blank: { at: 1, options: ['morr', 'mo'] } },
      { word: 'usually', sentence: 'I usually wake up early.', chunks: ['u', 'su', 'al', 'ly'], distractors: ['usualy', 'usally'], blank: { at: 2, options: ['el', 'ual'] } },
      { word: 'weather', sentence: 'The weather turned cold.', chunks: ['weath', 'er'], distractors: ['wether', 'wheather'], blank: { at: 0, options: ['weth', 'wheath'] } },
      { word: 'adventure', sentence: 'We went on a fun adventure in the woods.', chunks: ['ad', 'ven', 'ture'], distractors: ['advencher', 'adventer'], blank: { at: 2, options: ['cher', 'chur'] } },
      { word: 'mountain', sentence: 'The mountain trail was steep and rocky.', chunks: ['moun', 'tain'], distractors: ['mountin', 'mowntain'], blank: { at: 1, options: ['ten', 'tin'] } },
      { word: 'thunder', sentence: 'Thunder rumbled across the valley.', chunks: ['thun', 'der'], distractors: ['thundar', 'thunnder'], blank: { at: 1, options: ['dar', 'dur'] } },
      { word: 'anchor', sentence: 'The boat dropped its anchor at dusk.', chunks: ['an', 'chor'], distractors: ['ancor', 'anker'], blank: { at: 1, options: ['ker', 'cor'] } },
      { word: 'picnic', sentence: 'We packed sandwiches for the picnic.', chunks: ['pic', 'nic'], distractors: ['picknic', 'picnick'], blank: { at: 0, options: ['pick', 'pik'] } },
      { word: 'lantern', sentence: 'The lantern glowed softly by the tent.', chunks: ['lan', 'tern'], distractors: ['lanturn', 'lantirn'], blank: { at: 1, options: ['turn', 'tirn'] } },
      { word: 'whistle', sentence: 'The coach blew the whistle to start practice.', chunks: ['whis', 'tle'], distractors: ['wisle', 'whissel'], blank: { at: 1, options: ['tel', 'tal'] } },
      { word: 'bicycle', sentence: 'He rides his bicycle to school every day.', chunks: ['bi', 'cy', 'cle'], distractors: ['bycicle', 'bicicle'], blank: { at: 1, options: ['ci', 'sy'] } },
      { word: 'journey', sentence: 'The journey took three long days.', chunks: ['jour', 'ney'], distractors: ['jerney', 'journy'], blank: { at: 0, options: ['jer', 'jor'] } },
      { word: 'castle', sentence: 'The castle sat high on the hill.', chunks: ['cas', 'tle'], distractors: ['cassle', 'castel'], blank: { at: 1, options: ['tel', 'tal'] } },
      { word: 'forest', sentence: 'Deer wandered through the quiet forest.', chunks: ['for', 'est'], distractors: ['forrest', 'forist'], blank: { at: 1, options: ['ist', 'esst'] } },
      { word: 'island', sentence: 'A small island sat in the middle of the lake.', chunks: ['is', 'land'], distractors: ['iland', 'ileand'], blank: { at: 0, options: ['i', 'ie'] } },
      { word: 'pumpkin', sentence: 'We carved a pumpkin for the fall party.', chunks: ['pump', 'kin'], distractors: ['punkin', 'pumkin'], blank: { at: 0, options: ['pum', 'pom'] } },
      { word: 'dolphin', sentence: 'The dolphin leaped out of the water.', chunks: ['dol', 'phin'], distractors: ['dolfin', 'dolphine'], blank: { at: 1, options: ['fin', 'fyn'] } },
      { word: 'rainbow', sentence: 'A rainbow appeared after the storm.', chunks: ['rain', 'bow'], distractors: ['rainbo', 'raynbow'], blank: { at: 1, options: ['boe', 'bo'] } },
      { word: 'volcano', sentence: 'The volcano has been quiet for years.', chunks: ['vol', 'ca', 'no'], distractors: ['volcanoe', 'vulcano'], blank: { at: 2, options: ['know', 'noe'] } },
      { word: 'skeleton', sentence: 'The museum has a dinosaur skeleton on display.', chunks: ['skel', 'e', 'ton'], distractors: ['skelaton', 'skelliton'], blank: { at: 1, options: ['a', 'i'] } },
      { word: 'triangle', sentence: 'Draw a triangle with three equal sides.', chunks: ['tri', 'an', 'gle'], distractors: ['trianggle', 'triangel'], blank: { at: 2, options: ['gel', 'gal'] } },
      { word: 'hospital', sentence: 'My uncle works at the hospital downtown.', chunks: ['hos', 'pi', 'tal'], distractors: ['hospitel', 'hosspital'], blank: { at: 2, options: ['tel', 'tul'] } },
      { word: 'elephant', sentence: 'The elephant sprayed water with its trunk.', chunks: ['el', 'e', 'phant'], distractors: ['elefant', 'elphant'], blank: { at: 2, options: ['fant', 'fent'] } },
      { word: 'umbrella', sentence: 'Grab an umbrella before you go outside.', chunks: ['um', 'brel', 'la'], distractors: ['umbrela', 'umbrellla'], blank: { at: 1, options: ['brell', 'brill'] } },
      { word: 'chocolate', sentence: 'She melted chocolate for the cookies.', chunks: ['choc', 'o', 'late'], distractors: ['choclate', 'chocolote'], blank: { at: 1, options: ['a', 'e'] } },
      { word: 'accident', sentence: 'The spilled juice was just an accident.', chunks: ['ac', 'ci', 'dent'], distractors: ['accadent', 'axident'], blank: { at: 1, options: ['ce', 'si'] } },
      { word: 'balance', sentence: 'She tried to balance on the log.', chunks: ['bal', 'ance'], distractors: ['ballance', 'balanse'], blank: { at: 1, options: ['ence', 'anse'] } },
      { word: 'capture', sentence: 'The camera can capture the sunset colors.', chunks: ['cap', 'ture'], distractors: ['capcher', 'captur'], blank: { at: 1, options: ['cher', 'chur'] } },
      { word: 'century', sentence: 'The old clock is over a century old.', chunks: ['cen', 'tu', 'ry'], distractors: ['centery', 'centry'], blank: { at: 1, options: ['ta', 'chu'] } },
      { word: 'distance', sentence: 'We measured the distance between two trees.', chunks: ['dis', 'tance'], distractors: ['distence', 'distanse'], blank: { at: 1, options: ['tence', 'tanse'] } },
      { word: 'energy', sentence: 'Running gave her lots of energy.', chunks: ['en', 'er', 'gy'], distractors: ['energie', 'enirgy'], blank: { at: 2, options: ['gie', 'jy'] } },
      { word: 'fortune', sentence: 'The fortune cookie held a funny message.', chunks: ['for', 'tune'], distractors: ['forchune', 'fortoon'], blank: { at: 1, options: ['toon', 'chune'] } },
      { word: 'gravity', sentence: 'Gravity pulls the ball back down.', chunks: ['grav', 'i', 'ty'], distractors: ['gravety', 'gravitty'], blank: { at: 1, options: ['e', 'a'] } },
      { word: 'horizon', sentence: 'The sun dipped below the horizon.', chunks: ['ho', 'ri', 'zon'], distractors: ['horrizon', 'horizen'], blank: { at: 2, options: ['zen', 'son'] } },
      { word: 'curious', sentence: 'The curious cat peeked into the box.', chunks: ['cu', 'ri', 'ous'], distractors: ['curius', 'curiuos'], blank: { at: 2, options: ['us', 'ious'] } },
    ],
  },
  {
    id: 'trailblazer',
    label: 'Trailblazer Ridge',
    grades: 'Grades 4–5',
    description: 'Tricky roots and letter patterns',
    color: '#e28b4a',
    icon: '⛰️',
    words: [
      { word: 'necessary', sentence: 'Water is necessary on a long hike.', chunks: ['nec', 'es', 'sar', 'y'], distractors: ['neccessary', 'necessery'], blank: { at: 2, options: ['ser', 'sarr'] } },
      { word: 'separate', sentence: 'Put the papers in separate piles.', chunks: ['sep', 'a', 'rate'], distractors: ['seperate', 'seperrate'], blank: { at: 1, options: ['e', 'o'] } },
      { word: 'environment', sentence: 'We can help protect the environment.', chunks: ['en', 'vi', 'ron', 'ment'], distractors: ['enviroment', 'environmant'], blank: { at: 2, options: ['ren', 'rn'] } },
      { word: 'knowledge', sentence: 'Reading builds knowledge.', chunks: ['know', 'ledge'], distractors: ['knowlege', 'nolidge'], blank: { at: 1, options: ['lege', 'lidge'] } },
      { word: 'temperature', sentence: 'The temperature dropped overnight.', chunks: ['tem', 'per', 'a', 'ture'], distractors: ['temprature', 'tempereture'], blank: { at: 3, options: ['chure', 'tur'] } },
      { word: 'especially', sentence: 'I like fruit, especially peaches.', chunks: ['es', 'pe', 'cial', 'ly'], distractors: ['expecially', 'especialy'], blank: { at: 2, options: ['tial', 'sial'] } },
      { word: 'opportunity', sentence: 'The club gave me an opportunity to lead.', chunks: ['op', 'por', 'tu', 'ni', 'ty'], distractors: ['oportunity', 'oppertunity'], blank: { at: 0, options: ['opp', 'ap'] } },
      { word: 'immediately', sentence: 'We left immediately after the bell.', chunks: ['im', 'me', 'di', 'ate', 'ly'], distractors: ['imediately', 'immediatly'], blank: { at: 3, options: ['at', 'iate'] } },
      { word: 'definitely', sentence: 'I will definitely finish the chapter.', chunks: ['def', 'i', 'nite', 'ly'], distractors: ['definately', 'definatly'], blank: { at: 1, options: ['a', 'e'] } },
      { word: 'government', sentence: 'The government meets in that building.', chunks: ['gov', 'ern', 'ment'], distractors: ['goverment', 'govenment'], blank: { at: 1, options: ['ren', 'en'] } },
      { word: 'restaurant', sentence: 'We ate at a new restaurant.', chunks: ['res', 'tau', 'rant'], distractors: ['resturant', 'restraunt'], blank: { at: 1, options: ['tu', 'ta'] } },
      { word: 'business', sentence: 'My aunt runs a small business.', chunks: ['busi', 'ness'], distractors: ['buisness', 'bussiness'], blank: { at: 0, options: ['bisi', 'buis'] } },
      { word: 'beginning', sentence: 'The beginning of the book was slow.', chunks: ['be', 'gin', 'ning'], distractors: ['begining', 'beggining'], blank: { at: 2, options: ['ing', 'nning'] } },
      { word: 'familiar', sentence: 'That song sounds familiar.', chunks: ['fa', 'mil', 'iar'], distractors: ['familar', 'familier'], blank: { at: 2, options: ['ier', 'air'] } },
      { word: 'sincerely', sentence: 'I sincerely hope you win.', chunks: ['sin', 'cere', 'ly'], distractors: ['sincerly', 'sincerley'], blank: { at: 1, options: ['sere', 'ceer'] } },
      { word: 'library', sentence: 'The library is open until six.', chunks: ['li', 'brar', 'y'], distractors: ['libary', 'libraray'], blank: { at: 1, options: ['bary', 'brer'] } },
      { word: 'although', sentence: 'Although it rained, we hiked on.', chunks: ['al', 'though'], distractors: ['allthough', 'althogh'], blank: { at: 1, options: ['thogh', 'tho'] } },
      { word: 'argument', sentence: 'They settled the argument calmly.', chunks: ['ar', 'gu', 'ment'], distractors: ['arguement', 'argumant'], blank: { at: 1, options: ['gue', 'ga'] } },
      { word: 'attention', sentence: 'Please pay attention to the map.', chunks: ['at', 'ten', 'tion'], distractors: ['attension', 'atention'], blank: { at: 2, options: ['sion', 'shun'] } },
      { word: 'certainly', sentence: 'I will certainly be at the gate.', chunks: ['cer', 'tain', 'ly'], distractors: ['certinly', 'certainley'], blank: { at: 1, options: ['ten', 'tian'] } },
      { word: 'character', sentence: 'My favorite character is the fox.', chunks: ['char', 'ac', 'ter'], distractors: ['caracter', 'charactor'], blank: { at: 0, options: ['car', 'chair'] } },
      { word: 'comfortable', sentence: 'These boots are comfortable.', chunks: ['com', 'fort', 'a', 'ble'], distractors: ['comfterble', 'comfortible'], blank: { at: 3, options: ['bel', 'bal'] } },
      { word: 'difficult', sentence: 'The last puzzle was difficult.', chunks: ['dif', 'fi', 'cult'], distractors: ['dificult', 'difficualt'], blank: { at: 1, options: ['fe', 'fu'] } },
      { word: 'experience', sentence: 'Camping was a new experience.', chunks: ['ex', 'pe', 'ri', 'ence'], distractors: ['experiance', 'expierence'], blank: { at: 3, options: ['ance', 'ense'] } },
      { word: 'grateful', sentence: 'I am grateful for your help.', chunks: ['grate', 'ful'], distractors: ['greatful', 'gratefull'], blank: { at: 0, options: ['great', 'grat'] } },
      { word: 'happened', sentence: 'Tell me exactly what happened.', chunks: ['hap', 'pened'], distractors: ['happend', 'hapened'], blank: { at: 1, options: ['pend', 'panned'] } },
      { word: 'interesting', sentence: 'That was an interesting fact.', chunks: ['in', 'ter', 'est', 'ing'], distractors: ['intresting', 'interresting'], blank: { at: 1, options: ['tre', 'tur'] } },
      { word: 'language', sentence: 'She is learning a new language.', chunks: ['lan', 'guage'], distractors: ['langauge', 'languge'], blank: { at: 1, options: ['gauge', 'guge'] } },
      { word: 'medicine', sentence: 'The medicine tasted bitter.', chunks: ['med', 'i', 'cine'], distractors: ['medecine', 'medicin'], blank: { at: 1, options: ['a', 'e'] } },
      { word: 'quarter', sentence: 'A quarter of the pie is left.', chunks: ['quar', 'ter'], distractors: ['quater', 'quartar'], blank: { at: 0, options: ['qua', 'quor'] } },
      { word: 'reference', sentence: 'Use the atlas as a reference.', chunks: ['ref', 'er', 'ence'], distractors: ['referrence', 'referance'], blank: { at: 2, options: ['ance', 'ense'] } },
      { word: 'schedule', sentence: 'Check the schedule for the bus.', chunks: ['sched', 'ule'], distractors: ['schedual', 'shedule'], blank: { at: 0, options: ['shed', 'sked'] } },
      { word: 'mischievous', sentence: 'The mischievous puppy hid my shoe.', chunks: ['mis', 'chie', 'vous'], distractors: ['mischievious', 'mischevous'], blank: { at: 1, options: ['chei', 'chev'] } },
      { word: 'vehicle', sentence: 'We rode in a rescue vehicle.', chunks: ['ve', 'hi', 'cle'], distractors: ['vehicel', 'vehcle'], blank: { at: 1, options: ['i', 'hy'] } },
      { word: 'rhyme', sentence: 'This poem has a perfect rhyme.', chunks: ['rh', 'yme'], distractors: ['ryme', 'rime'], blank: { at: 0, options: ['r', 'wr'] } },
      { word: 'surround', sentence: 'Tall trees surround the cabin.', chunks: ['sur', 'round'], distractors: ['suround', 'surrownd'], blank: { at: 0, options: ['ser', 'sir'] } },
      { word: 'nuisance', sentence: 'The buzzing fly was a real nuisance.', chunks: ['nui', 'sance'], distractors: ['nusance', 'nuisence'], blank: { at: 0, options: ['new', 'nu'] } },
      { word: 'license', sentence: 'She proudly showed her fishing license.', chunks: ['li', 'cense'], distractors: ['lisence', 'licance'], blank: { at: 1, options: ['sence', 'sense'] } },
      { word: 'villain', sentence: 'The story needed a clever villain.', chunks: ['vil', 'lain'], distractors: ['villan', 'villian'], blank: { at: 1, options: ['lan', 'lian'] } },
      { word: 'campaign', sentence: 'The class ran a recycling campaign.', chunks: ['cam', 'paign'], distractors: ['campain', 'campaigne'], blank: { at: 1, options: ['pain', 'pane'] } },
      { word: 'courageous', sentence: 'The firefighter made a courageous rescue.', chunks: ['cour', 'a', 'geous'], distractors: ['courageus', 'couragous'], blank: { at: 2, options: ['gous', 'jeous'] } },
      { word: 'laboratory', sentence: 'Scientists tested the sample in the laboratory.', chunks: ['lab', 'o', 'ra', 'tory'], distractors: ['labratory', 'laboritory'], blank: { at: 1, options: ['a', 'e'] } },
      { word: 'mysterious', sentence: 'A mysterious light appeared in the fog.', chunks: ['mys', 'te', 'ri', 'ous'], distractors: ['misterious', 'mysteryous'], blank: { at: 0, options: ['mis', 'mes'] } },
      { word: 'jealous', sentence: 'He felt jealous of her new bike.', chunks: ['jeal', 'ous'], distractors: ['jelous', 'gealous'], blank: { at: 0, options: ['jel', 'geal'] } },
      { word: 'luxury', sentence: 'The hotel felt like pure luxury.', chunks: ['lux', 'u', 'ry'], distractors: ['luxery', 'luxary'], blank: { at: 1, options: ['e', 'a'] } },
      { word: 'muscle', sentence: 'He flexed his arm muscle.', chunks: ['mus', 'cle'], distractors: ['mussel', 'muscel'], blank: { at: 1, options: ['cel', 'kle'] } },
      { word: 'column', sentence: 'A tall column held up the porch roof.', chunks: ['col', 'umn'], distractors: ['collumn', 'colum'], blank: { at: 1, options: ['um', 'umm'] } },
      { word: 'cushion', sentence: 'She fluffed the soft cushion.', chunks: ['cu', 'shion'], distractors: ['cushon', 'cussion'], blank: { at: 1, options: ['tion', 'sion'] } },
      { word: 'eighth', sentence: 'He finished in eighth place.', chunks: ['eigh', 'th'], distractors: ['eigth', 'eightth'], blank: { at: 0, options: ['eig', 'aigh'] } },
      { word: 'fascinate', sentence: 'The magic trick will fascinate the crowd.', chunks: ['fas', 'ci', 'nate'], distractors: ['fassinate', 'facinate'], blank: { at: 1, options: ['si', 'ce'] } },
      { word: 'genuine', sentence: 'Her smile was warm and genuine.', chunks: ['gen', 'u', 'ine'], distractors: ['genuwine', 'genuin'], blank: { at: 1, options: ['ew', 'oo'] } },
      { word: 'hesitate', sentence: 'Don\'t hesitate to ask for help.', chunks: ['hes', 'i', 'tate'], distractors: ['hesatate', 'hessitate'], blank: { at: 1, options: ['a', 'e'] } },
      { word: 'illustrate', sentence: 'The artist will illustrate the story.', chunks: ['il', 'lus', 'trate'], distractors: ['ilustrate', 'illustrait'], blank: { at: 0, options: ['ill', 'el'] } },
      { word: 'lightning', sentence: 'Lightning flashed across the sky.', chunks: ['light', 'ning'], distractors: ['lightening', 'litning'], blank: { at: 0, options: ['lite', 'lit'] } },
      { word: 'naughty', sentence: 'The naughty puppy chewed a shoe.', chunks: ['naugh', 'ty'], distractors: ['noughty', 'naughtty'], blank: { at: 0, options: ['nau', 'nogh'] } },
      { word: 'obedient', sentence: 'The obedient dog sat right away.', chunks: ['o', 'be', 'di', 'ent'], distractors: ['obediant', 'obedeint'], blank: { at: 3, options: ['ant', 'int'] } },
      { word: 'pastime', sentence: 'Reading is her favorite pastime.', chunks: ['pas', 'time'], distractors: ['passtime', 'pasttime'], blank: { at: 0, options: ['past', 'pass'] } },
      { word: 'rehearse', sentence: 'We rehearse the play after school.', chunks: ['re', 'hearse'], distractors: ['reherse', 'rehurse'], blank: { at: 1, options: ['herse', 'hurse'] } },
      { word: 'solemn', sentence: 'He made a solemn promise.', chunks: ['sol', 'emn'], distractors: ['solem', 'sollemn'], blank: { at: 1, options: ['em', 'emm'] } },
      { word: 'twelfth', sentence: 'Today is her twelfth birthday.', chunks: ['twelf', 'th'], distractors: ['twelth', 'twelfeth'], blank: { at: 0, options: ['twelv', 'twelfe'] } },
      { word: 'vaccine', sentence: 'The nurse gave the flu vaccine.', chunks: ['vac', 'cine'], distractors: ['vaccien', 'vacine'], blank: { at: 1, options: ['ceen', 'seen'] } },
      { word: 'handkerchief', sentence: 'He wiped his nose with a handkerchief.', chunks: ['hand', 'ker', 'chief'], distractors: ['hankerchief', 'handkerchef'], blank: { at: 2, options: ['cheif', 'chef'] } },
      { word: 'mosquito', sentence: 'A mosquito buzzed near the tent.', chunks: ['mos', 'qui', 'to'], distractors: ['moskito', 'musquito'], blank: { at: 1, options: ['ki', 'qi'] } },
      { word: 'scissors', sentence: 'Use the scissors to cut the paper.', chunks: ['scis', 'sors'], distractors: ['sissors', 'scisors'], blank: { at: 0, options: ['sis', 'siz'] } },
    ],
  },
  {
    id: 'summit',
    label: 'Summit Challenge',
    grades: 'Grades 5–6',
    description: 'Advanced words for confident climbers',
    color: '#8d6aae',
    icon: '🏔️',
    words: [
      { word: 'accommodate', sentence: 'The room can accommodate twelve people.', chunks: ['ac', 'com', 'mo', 'date'], distractors: ['acommodate', 'accomodate'], blank: { at: 1, options: ['co', 'comm'] } },
      { word: 'conscience', sentence: 'My conscience told me to be honest.', chunks: ['con', 'science'], distractors: ['concience', 'consciense'], blank: { at: 1, options: ['sience', 'scence'] } },
      { word: 'embarrass', sentence: 'A small mistake does not have to embarrass you.', chunks: ['em', 'bar', 'rass'], distractors: ['embarass', 'embarras'], blank: { at: 2, options: ['ras', 'rasse'] } },
      { word: 'rhythm', sentence: 'The drummer kept a steady rhythm.', chunks: ['rhy', 'thm'], distractors: ['rythm', 'rhythum'], blank: { at: 0, options: ['ry', 'rhi'] } },
      { word: 'privilege', sentence: 'It is a privilege to join the team.', chunks: ['priv', 'i', 'lege'], distractors: ['privelege', 'priviledge'], blank: { at: 2, options: ['ledge', 'lige'] } },
      { word: 'recommend', sentence: 'I recommend this mystery book.', chunks: ['rec', 'om', 'mend'], distractors: ['reccomend', 'recomend'], blank: { at: 1, options: ['omm', 'o'] } },
      { word: 'occasionally', sentence: 'We occasionally eat breakfast outside.', chunks: ['oc', 'ca', 'sion', 'al', 'ly'], distractors: ['ocassionally', 'occasionaly'], blank: { at: 2, options: ['tion', 'shion'] } },
      { word: 'pronunciation', sentence: 'The dictionary shows the pronunciation.', chunks: ['pro', 'nun', 'ci', 'a', 'tion'], distractors: ['pronounciation', 'pronuncation'], blank: { at: 1, options: ['noun', 'nunn'] } },
      { word: 'maintenance', sentence: 'The bridge is closed for maintenance.', chunks: ['main', 'te', 'nance'], distractors: ['maintanance', 'maintenence'], blank: { at: 1, options: ['ta', 'ti'] } },
      { word: 'questionnaire', sentence: 'Please fill out the questionnaire.', chunks: ['ques', 'tion', 'naire'], distractors: ['questionaire', 'questionnare'], blank: { at: 2, options: ['nare', 'nair'] } },
      { word: 'independent', sentence: 'She is an independent reader now.', chunks: ['in', 'de', 'pend', 'ent'], distractors: ['independant', 'indepindent'], blank: { at: 3, options: ['ant', 'int'] } },
      { word: 'achievement', sentence: 'Finishing the race was an achievement.', chunks: ['a', 'chieve', 'ment'], distractors: ['acheivement', 'achievment'], blank: { at: 1, options: ['cheive', 'chive'] } },
      { word: 'guarantee', sentence: 'I cannot guarantee the weather.', chunks: ['guar', 'an', 'tee'], distractors: ['garantee', 'guarentee'], blank: { at: 0, options: ['gar', 'guer'] } },
      { word: 'parallel', sentence: 'The two trails run parallel for a mile.', chunks: ['par', 'al', 'lel'], distractors: ['paralell', 'parralel'], blank: { at: 2, options: ['lell', 'llel'] } },
      { word: 'vacuum', sentence: 'Please vacuum the rug before dinner.', chunks: ['vac', 'uum'], distractors: ['vaccum', 'vacume'], blank: { at: 1, options: ['um', 'uom'] } },
      { word: 'exaggerate', sentence: 'Try not to exaggerate the story.', chunks: ['ex', 'ag', 'ger', 'ate'], distractors: ['exagerate', 'exaggarate'], blank: { at: 1, options: ['agg', 'a'] } },
      { word: 'acknowledge', sentence: 'Please acknowledge the message.', chunks: ['ac', 'knowl', 'edge'], distractors: ['aknowledge', 'acknowlege'], blank: { at: 1, options: ['nowl', 'knowel'] } },
      { word: 'apparent', sentence: 'The problem became apparent quickly.', chunks: ['ap', 'par', 'ent'], distractors: ['aparent', 'apparant'], blank: { at: 2, options: ['ant', 'int'] } },
      { word: 'category', sentence: 'Pick a category for your report.', chunks: ['cat', 'e', 'go', 'ry'], distractors: ['catagory', 'cathegory'], blank: { at: 1, options: ['a', 'i'] } },
      { word: 'cemetery', sentence: 'The old cemetery sits on the hill.', chunks: ['cem', 'e', 'ter', 'y'], distractors: ['cemetary', 'cemetry'], blank: { at: 2, options: ['tar', 'tery'] } },
      { word: 'committee', sentence: 'The committee met on Friday.', chunks: ['com', 'mit', 'tee'], distractors: ['commitee', 'comittee'], blank: { at: 2, options: ['te', 'ttee'] } },
      { word: 'curiosity', sentence: 'Her curiosity led to a discovery.', chunks: ['cu', 'ri', 'os', 'ity'], distractors: ['curiousity', 'curiosety'], blank: { at: 2, options: ['ous', 'us'] } },
      { word: 'desperate', sentence: 'We were desperate for shade.', chunks: ['des', 'per', 'ate'], distractors: ['desparate', 'desprate'], blank: { at: 1, options: ['par', 'pir'] } },
      { word: 'existence', sentence: 'No one knew of its existence.', chunks: ['ex', 'ist', 'ence'], distractors: ['existance', 'existense'], blank: { at: 2, options: ['ance', 'ense'] } },
      { word: 'foreign', sentence: 'He studied a foreign alphabet.', chunks: ['for', 'eign'], distractors: ['foriegn', 'forign'], blank: { at: 1, options: ['ien', 'iegn'] } },
      { word: 'gauge', sentence: 'Check the fuel gauge before driving.', chunks: ['gau', 'ge'], distractors: ['guage', 'gage'], blank: { at: 0, options: ['gua', 'ga'] } },
      { word: 'humorous', sentence: 'The story was humorous.', chunks: ['hu', 'mor', 'ous'], distractors: ['humourous', 'humerous'], blank: { at: 1, options: ['mer', 'mour'] } },
      { word: 'jewelry', sentence: 'She kept her jewelry in a tin.', chunks: ['jew', 'el', 'ry'], distractors: ['jewlery', 'jewelery'], blank: { at: 1, options: ['le', 'al'] } },
      { word: 'leisure', sentence: 'We read at leisure on Sundays.', chunks: ['lei', 'sure'], distractors: ['liesure', 'leasure'], blank: { at: 0, options: ['lie', 'lea'] } },
      { word: 'noticeable', sentence: 'The change was noticeable.', chunks: ['no', 'tice', 'a', 'ble'], distractors: ['noticable', 'noticeble'], blank: { at: 2, options: ['e', 'i'] } },
      { word: 'persuade', sentence: 'Try to persuade the group.', chunks: ['per', 'suade'], distractors: ['pursuade', 'perswade'], blank: { at: 1, options: ['swade', 'suede'] } },
      { word: 'relevant', sentence: 'Only relevant facts belong here.', chunks: ['rel', 'e', 'vant'], distractors: ['relevent', 'revelant'], blank: { at: 2, options: ['vent', 'vint'] } },
      { word: 'possession', sentence: 'The trophy became her prized possession.', chunks: ['pos', 'ses', 'sion'], distractors: ['posession', 'possesion'], blank: { at: 1, options: ['sess', 'cess'] } },
      { word: 'conscious', sentence: 'She was conscious of every small sound.', chunks: ['con', 'scious'], distractors: ['concious', 'conscius'], blank: { at: 1, options: ['cious', 'shus'] } },
      { word: 'vicious', sentence: 'The dog gave a vicious bark at strangers.', chunks: ['vi', 'cious'], distractors: ['viscious', 'visious'], blank: { at: 1, options: ['tious', 'sious'] } },
      { word: 'resemblance', sentence: 'The twins bore a strong resemblance.', chunks: ['re', 'sem', 'blance'], distractors: ['resemblence', 'resemblanse'], blank: { at: 2, options: ['blence', 'blanse'] } },
      { word: 'outrageous', sentence: 'That price is outrageous for a small snack.', chunks: ['out', 'rage', 'ous'], distractors: ['outragous', 'outrageus'], blank: { at: 2, options: ['eous', 'us'] } },
      { word: 'gorgeous', sentence: 'The sunset over the lake was gorgeous.', chunks: ['gor', 'geous'], distractors: ['gorgous', 'gourgeous'], blank: { at: 1, options: ['gous', 'jeous'] } },
      { word: 'responsible', sentence: 'Be responsible for your own gear.', chunks: ['re', 'spon', 'si', 'ble'], distractors: ['responsable', 'responcible'], blank: { at: 2, options: ['ci', 'ce'] } },
      { word: 'flexible', sentence: 'The schedule is flexible this week.', chunks: ['flex', 'i', 'ble'], distractors: ['flexable', 'flexeble'], blank: { at: 2, options: ['able', 'bel'] } },
      { word: 'horrible', sentence: 'The traffic this morning was horrible.', chunks: ['hor', 'ri', 'ble'], distractors: ['horrable', 'horible'], blank: { at: 1, options: ['ry', 're'] } },
      { word: 'possible', sentence: 'Finish the puzzle as fast as possible.', chunks: ['pos', 'si', 'ble'], distractors: ['posible', 'possable'], blank: { at: 1, options: ['ci', 'see'] } },
      { word: 'available', sentence: 'Tickets are available at the front desk.', chunks: ['a', 'vail', 'a', 'ble'], distractors: ['availible', 'avaliable'], blank: { at: 3, options: ['bel', 'able'] } },
      { word: 'valuable', sentence: 'The old coin turned out to be valuable.', chunks: ['val', 'u', 'a', 'ble'], distractors: ['valubale', 'valuble'], blank: { at: 1, options: ['ou', 'oo'] } },
      { word: 'reasonable', sentence: 'That is a reasonable price for lunch.', chunks: ['rea', 'son', 'a', 'ble'], distractors: ['resonable', 'reasonible'], blank: { at: 1, options: ['sun', 'zon'] } },
      { word: 'miserable', sentence: 'Getting soaked in the rain felt miserable.', chunks: ['mis', 'er', 'a', 'ble'], distractors: ['miserible', 'misrable'], blank: { at: 2, options: ['e', 'i'] } },
      { word: 'vegetable', sentence: 'Carrots are my favorite vegetable.', chunks: ['veg', 'e', 'ta', 'ble'], distractors: ['vegtable', 'vegatable'], blank: { at: 2, options: ['te', 'tea'] } },
      { word: 'vengeance', sentence: 'The knight swore vengeance on the dragon in the story.', chunks: ['ven', 'geance'], distractors: ['vengance', 'vengeanse'], blank: { at: 1, options: ['gence', 'geanse'] } },
      { word: 'resistance', sentence: 'The old lock offered some resistance.', chunks: ['re', 'sis', 'tance'], distractors: ['resistence', 'resistanse'], blank: { at: 2, options: ['tence', 'tanse'] } },
      { word: 'assistance', sentence: 'Ask the librarian for assistance.', chunks: ['as', 'sis', 'tance'], distractors: ['assistence', 'asistance'], blank: { at: 2, options: ['tence', 'tanse'] } },
      { word: 'attendance', sentence: 'The teacher checks attendance each morning.', chunks: ['at', 'ten', 'dance'], distractors: ['attendence', 'atendance'], blank: { at: 2, options: ['dence', 'danse'] } },
      { word: 'appearance', sentence: 'His sudden appearance surprised everyone.', chunks: ['ap', 'pear', 'ance'], distractors: ['apearance', 'appearence'], blank: { at: 2, options: ['ence', 'anse'] } },
      { word: 'ignorance', sentence: 'Ignorance of the rule is no excuse.', chunks: ['ig', 'nor', 'ance'], distractors: ['ignorence', 'ignoranse'], blank: { at: 2, options: ['ence', 'anse'] } },
      { word: 'elegance', sentence: 'The dancer moved with elegance.', chunks: ['el', 'e', 'gance'], distractors: ['elegence', 'eligance'], blank: { at: 2, options: ['gence', 'ganse'] } },
      { word: 'fragrance', sentence: 'The fragrance of pine filled the cabin.', chunks: ['fra', 'grance'], distractors: ['fragrence', 'fragranse'], blank: { at: 1, options: ['grence', 'granse'] } },
      { word: 'allowance', sentence: 'She saves half of her allowance.', chunks: ['al', 'low', 'ance'], distractors: ['alowance', 'allowence'], blank: { at: 2, options: ['ence', 'anse'] } },
      { word: 'annoyance', sentence: 'The buzzing fly was a real annoyance.', chunks: ['an', 'noy', 'ance'], distractors: ['anoyance', 'annoyence'], blank: { at: 2, options: ['ence', 'anse'] } },
      { word: 'brilliance', sentence: 'Her plan showed real brilliance.', chunks: ['bril', 'li', 'ance'], distractors: ['brillance', 'brilliense'], blank: { at: 1, options: ['ly', 'le'] } },
      { word: 'confidence', sentence: 'Speak with confidence during the interview.', chunks: ['con', 'fi', 'dence'], distractors: ['confedence', 'confidance'], blank: { at: 2, options: ['dance', 'dense'] } },
      { word: 'convenience', sentence: 'The store is open for our convenience.', chunks: ['con', 've', 'ni', 'ence'], distractors: ['convenance', 'convience'], blank: { at: 3, options: ['ance', 'ense'] } },
      { word: 'patience', sentence: 'Fishing requires a lot of patience.', chunks: ['pa', 'tience'], distractors: ['patiance', 'pateince'], blank: { at: 1, options: ['tiance', 'cience'] } },
      { word: 'innocence', sentence: 'The jury believed in his innocence.', chunks: ['in', 'no', 'cence'], distractors: ['innocense', 'inocence'], blank: { at: 2, options: ['cense', 'sence'] } },
      { word: 'receipt', sentence: 'Keep the receipt in case you return it.', chunks: ['re', 'ceipt'], distractors: ['recipt', 'receit'], blank: { at: 1, options: ['cipt', 'ceit'] } },
      { word: 'irresistible', sentence: 'The warm bread smelled irresistible.', chunks: ['ir', 're', 'sist', 'ible'], distractors: ['irresistable', 'iresistible'], blank: { at: 3, options: ['able', 'ibel'] } },
    ],
  },
  {
    id: 'expedition',
    label: 'Expedition Peak',
    grades: 'Grades 7–8',
    description: 'Long words that trip up grown-ups too',
    color: '#3f7f8c',
    icon: '🧗',
    words: [
      { word: 'conscientious', sentence: 'She is a conscientious note taker.', chunks: ['con', 'sci', 'en', 'tious'], distractors: ['consciencious', 'conscientous'], blank: { at: 3, options: ['cious', 'tous'] } },
      { word: 'entrepreneur', sentence: 'The entrepreneur opened a bakery.', chunks: ['en', 'tre', 'pre', 'neur'], distractors: ['entreprenur', 'entrepeneur'], blank: { at: 3, options: ['nuer', 'nour'] } },
      { word: 'millennium', sentence: 'The castle stood for a millennium.', chunks: ['mil', 'len', 'ni', 'um'], distractors: ['milennium', 'millenium'], blank: { at: 1, options: ['lenn', 'le'] } },
      { word: 'perseverance', sentence: 'Her perseverance paid off at last.', chunks: ['per', 'se', 'ver', 'ance'], distractors: ['perseverence', 'persaverance'], blank: { at: 3, options: ['ence', 'anse'] } },
      { word: 'acquaintance', sentence: 'He is an acquaintance from camp.', chunks: ['ac', 'quain', 'tance'], distractors: ['aquaintance', 'acquaintence'], blank: { at: 1, options: ['quan', 'quian'] } },
      { word: 'bureaucracy', sentence: 'The permit was lost in bureaucracy.', chunks: ['bu', 'reau', 'cra', 'cy'], distractors: ['beaurocracy', 'bureacracy'], blank: { at: 1, options: ['rau', 'reo'] } },
      { word: 'hierarchy', sentence: 'The team has a clear hierarchy.', chunks: ['hi', 'er', 'ar', 'chy'], distractors: ['heirarchy', 'hierarcy'], blank: { at: 3, options: ['cy', 'key'] } },
      { word: 'inevitable', sentence: 'Rain on the trip felt inevitable.', chunks: ['in', 'ev', 'i', 'table'], distractors: ['inevitible', 'inevatable'], blank: { at: 3, options: ['tible', 'tabel'] } },
      { word: 'liaison', sentence: 'She acts as the liaison between classes.', chunks: ['li', 'ai', 'son'], distractors: ['liason', 'liasion'], blank: { at: 1, options: ['a', 'ia'] } },
      { word: 'miscellaneous', sentence: 'The drawer holds miscellaneous tools.', chunks: ['mis', 'cel', 'la', 'neous'], distractors: ['miscelaneous', 'miscellanious'], blank: { at: 3, options: ['nious', 'neus'] } },
      { word: 'occurrence', sentence: 'A blue moon is a rare occurrence.', chunks: ['oc', 'cur', 'rence'], distractors: ['occurence', 'ocurrence'], blank: { at: 2, options: ['ence', 'rance'] } },
      { word: 'pharaoh', sentence: 'The pharaoh ruled for forty years.', chunks: ['phar', 'aoh'], distractors: ['pharoah', 'faraoh'], blank: { at: 1, options: ['oah', 'aho'] } },
      { word: 'rendezvous', sentence: 'We set a rendezvous at the trailhead.', chunks: ['ren', 'dez', 'vous'], distractors: ['rendevous', 'rendezvouz'], blank: { at: 2, options: ['voo', 'vus'] } },
      { word: 'silhouette', sentence: 'A silhouette appeared against the sky.', chunks: ['sil', 'hou', 'ette'], distractors: ['sillhouette', 'silouette'], blank: { at: 1, options: ['ho', 'hue'] } },
      { word: 'threshold', sentence: 'She paused at the threshold of the cabin.', chunks: ['thresh', 'old'], distractors: ['threshhold', 'thresold'], blank: { at: 0, options: ['thres', 'thrash'] } },
      { word: 'unanimous', sentence: 'The vote was unanimous.', chunks: ['u', 'nan', 'i', 'mous'], distractors: ['unanamous', 'unaminous'], blank: { at: 3, options: ['mus', 'mious'] } },
      { word: 'accessible', sentence: 'The trail is accessible by bike.', chunks: ['ac', 'ces', 'si', 'ble'], distractors: ['accesible', 'acessible'], blank: { at: 1, options: ['ses', 'cess'] } },
      { word: 'ambiguous', sentence: 'The ending felt ambiguous.', chunks: ['am', 'big', 'u', 'ous'], distractors: ['ambigous', 'ambiguious'], blank: { at: 1, options: ['bigu', 'beg'] } },
      { word: 'camaraderie', sentence: 'The team built real camaraderie.', chunks: ['ca', 'ma', 'ra', 'derie'], distractors: ['comraderie', 'camaradery'], blank: { at: 3, options: ['dery', 'derry'] } },
      { word: 'connoisseur', sentence: 'She is a connoisseur of old maps.', chunks: ['con', 'nois', 'seur'], distractors: ['conoisseur', 'connoiseur'], blank: { at: 2, options: ['sur', 'seaur'] } },
      { word: 'definitive', sentence: 'There is no definitive ruling yet.', chunks: ['de', 'fin', 'i', 'tive'], distractors: ['definative', 'defenitive'], blank: { at: 2, options: ['a', 'e'] } },
      { word: 'exhilarate', sentence: 'Steep descents exhilarate him.', chunks: ['ex', 'hil', 'a', 'rate'], distractors: ['exhilerate', 'exilarate'], blank: { at: 1, options: ['hel', 'hill'] } },
      { word: 'fluorescent', sentence: 'The sign glowed fluorescent green.', chunks: ['fluo', 'res', 'cent'], distractors: ['flourescent', 'fluorescant'], blank: { at: 0, options: ['flou', 'flu'] } },
      { word: 'harass', sentence: 'Do not harass the wildlife.', chunks: ['ha', 'rass'], distractors: ['harrass', 'haras'], blank: { at: 1, options: ['ras', 'rasse'] } },
      { word: 'idiosyncrasy', sentence: 'That habit is a small idiosyncrasy.', chunks: ['id', 'i', 'o', 'syn', 'crasy'], distractors: ['idiosyncracy', 'ideosyncrasy'], blank: { at: 4, options: ['cracy', 'crazy'] } },
      { word: 'indispensable', sentence: 'A compass is indispensable out here.', chunks: ['in', 'dis', 'pen', 'sable'], distractors: ['indispensible', 'indispensabel'], blank: { at: 3, options: ['sible', 'sabel'] } },
      { word: 'maneuver', sentence: 'The pilot made a careful maneuver.', chunks: ['ma', 'neu', 'ver'], distractors: ['manuever', 'maneuvre'], blank: { at: 1, options: ['nue', 'noo'] } },
      { word: 'plagiarism', sentence: 'Citing sources prevents plagiarism.', chunks: ['pla', 'gia', 'rism'], distractors: ['plagerism', 'plagarism'], blank: { at: 1, options: ['ger', 'gar'] } },
      { word: 'reminiscent', sentence: 'The smell was reminiscent of pine.', chunks: ['rem', 'i', 'nis', 'cent'], distractors: ['reminicent', 'reminescent'], blank: { at: 3, options: ['sent', 'scent'] } },
      { word: 'supersede', sentence: 'New rules supersede the old ones.', chunks: ['su', 'per', 'sede'], distractors: ['supercede', 'superseed'], blank: { at: 2, options: ['cede', 'seed'] } },
      { word: 'vacillate', sentence: 'Do not vacillate at the summit.', chunks: ['vac', 'il', 'late'], distractors: ['vasillate', 'vacilate'], blank: { at: 1, options: ['ill', 'el'] } },
      { word: 'weird', sentence: 'That cloud has a weird shape.', chunks: ['we', 'ird'], distractors: ['wierd', 'weerd'], blank: { at: 1, options: ['ierd', 'eird'] } },
      { word: 'onomatopoeia', sentence: 'Buzz and hiss are examples of onomatopoeia.', chunks: ['on', 'o', 'mat', 'o', 'poe', 'ia'], distractors: ['onomatopeia', 'onamatopoeia'], blank: { at: 4, options: ['po', 'pow'] } },
      { word: 'bourgeois', sentence: 'The novel satirizes bourgeois taste.', chunks: ['bour', 'geois'], distractors: ['bourgeoise', 'borgeois'], blank: { at: 1, options: ['geoise', 'jeois'] } },
      { word: 'cappuccino', sentence: 'She ordered a cappuccino at the coffee shop.', chunks: ['cap', 'puc', 'ci', 'no'], distractors: ['capuccino', 'cappucino'], blank: { at: 1, options: ['puk', 'pucc'] } },
      { word: 'chrysanthemum', sentence: 'The chrysanthemum bloomed late in fall.', chunks: ['chry', 'san', 'the', 'mum'], distractors: ['chrysanthemem', 'chrysanthamum'], blank: { at: 2, options: ['tha', 'thi'] } },
      { word: 'psychology', sentence: 'She is studying psychology in college.', chunks: ['psy', 'chol', 'o', 'gy'], distractors: ['sychology', 'psycology'], blank: { at: 0, options: ['sy', 'psi'] } },
      { word: 'gnocchi', sentence: 'We made gnocchi from scratch for dinner.', chunks: ['gno', 'cchi'], distractors: ['nocchi', 'gnochi'], blank: { at: 1, options: ['chi', 'ccio'] } },
      { word: 'chauffeur', sentence: 'A chauffeur drove them to the airport.', chunks: ['chauf', 'feur'], distractors: ['shauffeur', 'chaufeur'], blank: { at: 1, options: ['fer', 'feure'] } },
      { word: 'entourage', sentence: 'The singer arrived with a large entourage.', chunks: ['en', 'tour', 'age'], distractors: ['ontourage', 'entorage'], blank: { at: 1, options: ['tor', 'toor'] } },
      { word: 'vignette', sentence: 'The essay opens with a short vignette.', chunks: ['vig', 'nette'], distractors: ['vinette', 'vignete'], blank: { at: 1, options: ['nete', 'net'] } },
      { word: 'rapport', sentence: 'The coach built rapport with the team.', chunks: ['rap', 'port'], distractors: ['raport', 'repport'], blank: { at: 0, options: ['ra', 'rapp'] } },
      { word: 'bouquet', sentence: 'He gave her a bouquet of tulips.', chunks: ['bou', 'quet'], distractors: ['boquet', 'bouqet'], blank: { at: 1, options: ['ket', 'kwet'] } },
      { word: 'crescendo', sentence: 'The music built to a thunderous crescendo.', chunks: ['cres', 'cen', 'do'], distractors: ['crescendoe', 'cresendo'], blank: { at: 1, options: ['sen', 'can'] } },
      { word: 'exquisite', sentence: 'The necklace was exquisite work.', chunks: ['ex', 'qui', 'site'], distractors: ['excquisite', 'exquisit'], blank: { at: 1, options: ['que', 'ki'] } },
      { word: 'impeccable', sentence: 'Her manners were impeccable at dinner.', chunks: ['im', 'pec', 'ca', 'ble'], distractors: ['impecable', 'impeccible'], blank: { at: 3, options: ['able', 'bel'] } },
      { word: 'juxtaposition', sentence: 'The film uses juxtaposition to show contrast.', chunks: ['jux', 'ta', 'po', 'si', 'tion'], distractors: ['juxtoposition', 'juxtapossition'], blank: { at: 4, options: ['sion', 'shun'] } },
      { word: 'kaleidoscope', sentence: 'The kaleidoscope made colorful patterns.', chunks: ['ka', 'lei', 'do', 'scope'], distractors: ['kaliedoscope', 'kaleidascope'], blank: { at: 1, options: ['lie', 'lai'] } },
      { word: 'labyrinth', sentence: 'We got lost in the hedge labyrinth.', chunks: ['lab', 'y', 'rinth'], distractors: ['labrinth', 'labarynth'], blank: { at: 2, options: ['rynth', 'rinthe'] } },
      { word: 'lieutenant', sentence: 'The lieutenant gave the final order.', chunks: ['lieu', 'ten', 'ant'], distractors: ['leutenant', 'lieutenent'], blank: { at: 0, options: ['leu', 'liu'] } },
      { word: 'nauseous', sentence: 'The boat ride made him nauseous.', chunks: ['nau', 'se', 'ous'], distractors: ['nauseus', 'nautious'], blank: { at: 1, options: ['sea', 'zea'] } },
      { word: 'paradigm', sentence: 'This discovery caused a paradigm shift.', chunks: ['par', 'a', 'digm'], distractors: ['paradime', 'paradigmn'], blank: { at: 2, options: ['dime', 'digme'] } },
      { word: 'quintessential', sentence: 'Apple pie is a quintessential dessert.', chunks: ['quin', 'tes', 'sen', 'tial'], distractors: ['quintessencial', 'quintessentual'], blank: { at: 3, options: ['cial', 'shal'] } },
      { word: 'renaissance', sentence: 'Artists thrived during the renaissance.', chunks: ['re', 'nai', 'ssance'], distractors: ['renaisance', 'renaissence'], blank: { at: 2, options: ['sance', 'ssence'] } },
      { word: 'surveillance', sentence: 'Cameras provided surveillance of the lot.', chunks: ['sur', 'veil', 'lance'], distractors: ['surveilance', 'survaillance'], blank: { at: 1, options: ['vail', 'veal'] } },
      { word: 'synonymous', sentence: 'Quick is nearly synonymous with fast.', chunks: ['syn', 'on', 'y', 'mous'], distractors: ['synonimous', 'synonymus'], blank: { at: 2, options: ['i', 'ie'] } },
      { word: 'ubiquitous', sentence: 'Smartphones are now ubiquitous.', chunks: ['u', 'biq', 'ui', 'tous'], distractors: ['ubiqitous', 'ubiquitious'], blank: { at: 2, options: ['ue', 'wi'] } },
      { word: 'xenophobia', sentence: 'The lesson addressed xenophobia in history.', chunks: ['xen', 'o', 'pho', 'bia'], distractors: ['zenophobia', 'xenaphobia'], blank: { at: 0, options: ['zen', 'xin'] } },
      { word: 'zealous', sentence: 'The zealous fans cheered all night.', chunks: ['zeal', 'ous'], distractors: ['zelous', 'zealus'], blank: { at: 0, options: ['zeel', 'zele'] } },
      { word: 'archaeology', sentence: 'She studies archaeology at the museum.', chunks: ['ar', 'chae', 'ol', 'o', 'gy'], distractors: ['archeology', 'archaeologie'], blank: { at: 1, options: ['che', 'chea'] } },
      { word: 'camouflage', sentence: 'The lizard used camouflage to hide.', chunks: ['cam', 'ou', 'flage'], distractors: ['camoflage', 'camouflague'], blank: { at: 1, options: ['o', 'oo'] } },
      { word: 'chandelier', sentence: 'A crystal chandelier hung above the hall.', chunks: ['chan', 'de', 'lier'], distractors: ['chandalier', 'chandeleir'], blank: { at: 2, options: ['leir', 'liere'] } },
      { word: 'colonel', sentence: 'The colonel addressed the troops.', chunks: ['col', 'o', 'nel'], distractors: ['kernel', 'colonnel'], blank: { at: 1, options: ['e', 'a'] } },
      { word: 'facade', sentence: 'The building has a stone facade.', chunks: ['fa', 'cade'], distractors: ['facaade', 'fascade'], blank: { at: 1, options: ['cad', 'kade'] } },
    ],
  },
]

export const DEFAULT_TIER_ID = 'warmup'
