export const WORD_TIERS = [
  {
    id: 'warmup',
    label: 'Warm-up Woods',
    grades: 'Grades 2–3',
    description: 'Common words and friendly patterns',
    color: '#56a87f',
    words: [
      { word: 'because', sentence: 'I wore boots because it was raining.', chunks: ['be', 'cause'], distractors: ['becuase', 'becaus'] },
      { word: 'friend', sentence: 'My friend saved me a seat.', chunks: ['fri', 'end'], distractors: ['freind', 'frend'] },
      { word: 'people', sentence: 'Many people came to the game.', chunks: ['peo', 'ple'], distractors: ['peeple', 'pepole'] },
      { word: 'every', sentence: 'We read together every night.', chunks: ['ev', 'er', 'y'], distractors: ['evry', 'everey'] },
      { word: 'school', sentence: 'The school library has new books.', chunks: ['sch', 'ool'], distractors: ['scool', 'schole'] },
      { word: 'again', sentence: 'Please play that song again.', chunks: ['a', 'gain'], distractors: ['agen', 'agian'] },
      { word: 'answer', sentence: 'I knew the answer to the riddle.', chunks: ['an', 'swer'], distractors: ['anser', 'answere'] },
      { word: 'thought', sentence: 'I thought about the puzzle.', chunks: ['th', 'ought'], distractors: ['thot', 'thoughte'] },
    ],
  },
  {
    id: 'explorer',
    label: 'Explorer Creek',
    grades: 'Grades 3–4',
    description: 'Vowels, endings, and longer words',
    color: '#428fa4',
    words: [
      { word: 'different', sentence: 'Each snowflake looks different.', chunks: ['dif', 'fer', 'ent'], distractors: ['diffrent', 'differant'] },
      { word: 'important', sentence: 'Practice is important when learning.', chunks: ['im', 'por', 'tant'], distractors: ['importent', 'inportant'] },
      { word: 'favorite', sentence: 'Blue is my favorite color.', chunks: ['fa', 'vor', 'ite'], distractors: ['faverite', 'favorit'] },
      { word: 'beautiful', sentence: 'The sunset was beautiful.', chunks: ['beau', 'ti', 'ful'], distractors: ['beautifull', 'butiful'] },
      { word: 'probably', sentence: 'We will probably leave after lunch.', chunks: ['prob', 'a', 'bly'], distractors: ['probly', 'probabaly'] },
      { word: 'remember', sentence: 'Remember to bring your jacket.', chunks: ['re', 'mem', 'ber'], distractors: ['remeber', 'remmember'] },
      { word: 'surprise', sentence: 'The party was a surprise.', chunks: ['sur', 'prise'], distractors: ['suprise', 'surprize'] },
      { word: 'calendar', sentence: 'Mark the date on the calendar.', chunks: ['cal', 'en', 'dar'], distractors: ['calender', 'calandar'] },
    ],
  },
  {
    id: 'trailblazer',
    label: 'Trailblazer Ridge',
    grades: 'Grades 4–5',
    description: 'Tricky roots and letter patterns',
    color: '#e28b4a',
    words: [
      { word: 'necessary', sentence: 'Water is necessary on a long hike.', chunks: ['nec', 'es', 'sar', 'y'], distractors: ['neccessary', 'necessery'] },
      { word: 'separate', sentence: 'Put the papers in separate piles.', chunks: ['sep', 'a', 'rate'], distractors: ['seperate', 'seperrate'] },
      { word: 'environment', sentence: 'We can help protect the environment.', chunks: ['en', 'vi', 'ron', 'ment'], distractors: ['enviroment', 'environmant'] },
      { word: 'knowledge', sentence: 'Reading builds knowledge.', chunks: ['know', 'ledge'], distractors: ['knowlege', 'nolidge'] },
      { word: 'temperature', sentence: 'The temperature dropped overnight.', chunks: ['tem', 'per', 'a', 'ture'], distractors: ['temprature', 'tempereture'] },
      { word: 'especially', sentence: 'I like fruit, especially peaches.', chunks: ['es', 'pe', 'cial', 'ly'], distractors: ['expecially', 'especialy'] },
      { word: 'opportunity', sentence: 'The club gave me an opportunity to lead.', chunks: ['op', 'por', 'tu', 'ni', 'ty'], distractors: ['oportunity', 'oppertunity'] },
      { word: 'immediately', sentence: 'We left immediately after the bell.', chunks: ['im', 'me', 'di', 'ate', 'ly'], distractors: ['imediately', 'immediatly'] },
    ],
  },
  {
    id: 'summit',
    label: 'Summit Challenge',
    grades: 'Grades 5–6',
    description: 'Advanced words for confident climbers',
    color: '#8d6aae',
    words: [
      { word: 'accommodate', sentence: 'The room can accommodate twelve people.', chunks: ['ac', 'com', 'mo', 'date'], distractors: ['acommodate', 'accomodate'] },
      { word: 'conscience', sentence: 'My conscience told me to be honest.', chunks: ['con', 'science'], distractors: ['concience', 'consciense'] },
      { word: 'embarrass', sentence: 'A small mistake does not have to embarrass you.', chunks: ['em', 'bar', 'rass'], distractors: ['embarass', 'embarras'] },
      { word: 'rhythm', sentence: 'The drummer kept a steady rhythm.', chunks: ['rhy', 'thm'], distractors: ['rythm', 'rhythum'] },
      { word: 'privilege', sentence: 'It is a privilege to join the team.', chunks: ['priv', 'i', 'lege'], distractors: ['privelege', 'priviledge'] },
      { word: 'recommend', sentence: 'I recommend this mystery book.', chunks: ['rec', 'om', 'mend'], distractors: ['reccomend', 'recomend'] },
      { word: 'occasionally', sentence: 'We occasionally eat breakfast outside.', chunks: ['oc', 'ca', 'sion', 'al', 'ly'], distractors: ['ocassionally', 'occasionaly'] },
      { word: 'pronunciation', sentence: 'The dictionary shows the pronunciation.', chunks: ['pro', 'nun', 'ci', 'a', 'tion'], distractors: ['pronounciation', 'pronuncation'] },
    ],
  },
]
