// `chunks` must rejoin exactly into `word`. `blank.at` is the index of the chunk
// to hide and `blank.options` are its decoys. Both decoys and `distractors` are
// hand-authored plausible misspellings — generated ones are non-words a player
// can rule out without knowing the spelling. src/game.test.js enforces all of it.
export const WORD_TIERS = [
  {
    id: 'basecamp',
    label: 'Base Camp',
    grades: 'Grades 1–2',
    description: 'First sight words and sound patterns',
    color: '#c9585f',
    icon: '⛺',
    words: [
      { word: 'said', sentence: 'She said hello to the new kid.', chunks: ['s', 'aid'], distractors: ['sed', 'sayd'], blank: { at: 1, options: ['ade', 'ayd'] } },
      { word: 'they', sentence: 'They packed snacks for the hike.', chunks: ['th', 'ey'], distractors: ['thay', 'thei'], blank: { at: 1, options: ['ay', 'ai'] } },
      { word: 'what', sentence: 'I know what to do next.', chunks: ['wh', 'at'], distractors: ['wut', 'whut'], blank: { at: 0, options: ['w', 'hw'] } },
      { word: 'come', sentence: 'Come to the campfire with us.', chunks: ['c', 'ome'], distractors: ['cum', 'kome'], blank: { at: 1, options: ['um', 'ume'] } },
      { word: 'some', sentence: 'Can I have some more paper?', chunks: ['s', 'ome'], distractors: ['sum', 'somme'], blank: { at: 1, options: ['um', 'ume'] } },
      { word: 'there', sentence: 'Look over there by the tree.', chunks: ['th', 'ere'], distractors: ['ther', 'thare'], blank: { at: 1, options: ['air', 'ear'] } },
      { word: 'where', sentence: 'Do you remember where we parked?', chunks: ['wh', 'ere'], distractors: ['wher', 'whare'], blank: { at: 1, options: ['air', 'ear'] } },
      { word: 'little', sentence: 'The little owl blinked twice.', chunks: ['lit', 'tle'], distractors: ['littel', 'litle'], blank: { at: 1, options: ['tel', 'tal'] } },
      { word: 'water', sentence: 'Please drink some water.', chunks: ['wa', 'ter'], distractors: ['watter', 'wader'], blank: { at: 1, options: ['tar', 'tor'] } },
      { word: 'after', sentence: 'We walk home after school.', chunks: ['af', 'ter'], distractors: ['affter', 'aftur'], blank: { at: 1, options: ['tar', 'tir'] } },
      { word: 'know', sentence: 'I know the way to camp.', chunks: ['kn', 'ow'], distractors: ['knoe', 'nowe'], blank: { at: 0, options: ['n', 'c'] } },
      { word: 'write', sentence: 'I write my name at the top.', chunks: ['wr', 'ite'], distractors: ['rite', 'writ'], blank: { at: 0, options: ['r', 'rh'] } },
      { word: 'many', sentence: 'How many stars can you count?', chunks: ['ma', 'ny'], distractors: ['meny', 'manny'], blank: { at: 0, options: ['me', 'mu'] } },
      { word: 'would', sentence: 'I would like a turn.', chunks: ['w', 'ould'], distractors: ['wuld', 'wold'], blank: { at: 1, options: ['uld', 'oud'] } },
      { word: 'their', sentence: 'The birds built their nest.', chunks: ['th', 'eir'], distractors: ['thier', 'thair'], blank: { at: 1, options: ['ier', 'air'] } },
      { word: 'about', sentence: 'This book is about a brave fox.', chunks: ['a', 'bout'], distractors: ['abowt', 'abot'], blank: { at: 1, options: ['bowt', 'bot'] } },
      { word: 'could', sentence: 'I could hear the rain on the roof.', chunks: ['c', 'ould'], distractors: ['cud', 'coud'], blank: { at: 1, options: ['uld', 'oud'] } },
      { word: 'should', sentence: 'We should leave soon.', chunks: ['sh', 'ould'], distractors: ['shud', 'shoud'], blank: { at: 0, options: ['sch', 'ch'] } },
      { word: 'does', sentence: 'She does her homework early.', chunks: ['d', 'oes'], distractors: ['duz', 'dose'], blank: { at: 1, options: ['uz', 'ose'] } },
      { word: 'goes', sentence: 'The bus goes past our street.', chunks: ['g', 'oes'], distractors: ['gose', 'gos'], blank: { at: 1, options: ['ose', 'os'] } },
      { word: 'very', sentence: 'The soup was very hot.', chunks: ['ver', 'y'], distractors: ['vary', 'verry'], blank: { at: 0, options: ['var', 'vur'] } },
      { word: 'from', sentence: 'I got a letter from my cousin.', chunks: ['fr', 'om'], distractors: ['form', 'frum'], blank: { at: 1, options: ['um', 'am'] } },
      { word: 'been', sentence: 'I have been to that park.', chunks: ['b', 'een'], distractors: ['ben', 'bean'], blank: { at: 1, options: ['ean', 'en'] } },
      { word: 'these', sentence: 'These apples are ripe.', chunks: ['th', 'ese'], distractors: ['thease', 'thes'], blank: { at: 1, options: ['ease', 'eze'] } },
      { word: 'those', sentence: 'Those clouds look heavy.', chunks: ['th', 'ose'], distractors: ['thoes', 'thoze'], blank: { at: 1, options: ['oes', 'oze'] } },
      { word: 'other', sentence: 'The other shoe is by the door.', chunks: ['oth', 'er'], distractors: ['othur', 'uther'], blank: { at: 1, options: ['ur', 'ar'] } },
      { word: 'under', sentence: 'The cat hid under the chair.', chunks: ['un', 'der'], distractors: ['unnder', 'undur'], blank: { at: 1, options: ['dur', 'dar'] } },
      { word: 'over', sentence: 'The bird flew over the fence.', chunks: ['o', 'ver'], distractors: ['ovur', 'overr'], blank: { at: 1, options: ['vur', 'var'] } },
      { word: 'before', sentence: 'Wash your hands before dinner.', chunks: ['be', 'fore'], distractors: ['befor', 'beefore'], blank: { at: 1, options: ['for', 'four'] } },
      { word: 'house', sentence: 'Our house has a blue door.', chunks: ['h', 'ouse'], distractors: ['hows', 'howse'], blank: { at: 1, options: ['ows', 'owse'] } },
      { word: 'mother', sentence: 'My mother reads to me at night.', chunks: ['moth', 'er'], distractors: ['muther', 'mothur'], blank: { at: 0, options: ['muth', 'mothe'] } },
      { word: 'father', sentence: 'My father packed the lunches.', chunks: ['fath', 'er'], distractors: ['fahter', 'fathur'], blank: { at: 0, options: ['fauth', 'feth'] } },
    ],
  },
  {
    id: 'warmup',
    label: 'Warm-up Woods',
    grades: 'Grades 2–3',
    description: 'Common words and friendly patterns',
    color: '#56a87f',
    icon: '🌲',
    words: [
      { word: 'because', sentence: 'I wore boots because it was raining.', chunks: ['be', 'cause'], distractors: ['becuase', 'becaus'], blank: { at: 1, options: ['cuase', 'caus'] } },
      { word: 'friend', sentence: 'My friend saved me a seat.', chunks: ['fri', 'end'], distractors: ['freind', 'frend'], blank: { at: 0, options: ['fre', 'fir'] } },
      { word: 'people', sentence: 'Many people came to the game.', chunks: ['peo', 'ple'], distractors: ['peeple', 'pepole'], blank: { at: 0, options: ['pea', 'pio'] } },
      { word: 'every', sentence: 'We read together every night.', chunks: ['ev', 'er', 'y'], distractors: ['evry', 'everey'], blank: { at: 1, options: ['ir', 'ur'] } },
      { word: 'school', sentence: 'The school library has new books.', chunks: ['sch', 'ool'], distractors: ['scool', 'schole'], blank: { at: 0, options: ['sc', 'sk'] } },
      { word: 'again', sentence: 'Please play that song again.', chunks: ['a', 'gain'], distractors: ['agen', 'agian'], blank: { at: 1, options: ['gian', 'gan'] } },
      { word: 'answer', sentence: 'I knew the answer to the riddle.', chunks: ['an', 'swer'], distractors: ['anser', 'answere'], blank: { at: 1, options: ['ser', 'sur'] } },
      { word: 'thought', sentence: 'I thought about the puzzle.', chunks: ['th', 'ought'], distractors: ['thot', 'thoughte'], blank: { at: 1, options: ['ot', 'aught'] } },
      { word: 'through', sentence: 'We hiked through the woods.', chunks: ['thr', 'ough'], distractors: ['thru', 'throught'], blank: { at: 1, options: ['ugh', 'ou'] } },
      { word: 'money', sentence: 'I saved money for a new book.', chunks: ['mon', 'ey'], distractors: ['mony', 'munny'], blank: { at: 1, options: ['y', 'ie'] } },
      { word: 'together', sentence: 'Let us read together tonight.', chunks: ['to', 'geth', 'er'], distractors: ['togather', 'togeather'], blank: { at: 1, options: ['gath', 'geath'] } },
      { word: 'morning', sentence: 'The morning air felt cool.', chunks: ['morn', 'ing'], distractors: ['moring', 'mornning'], blank: { at: 0, options: ['mourn', 'morne'] } },
      { word: 'children', sentence: 'The children lined up quietly.', chunks: ['chil', 'dren'], distractors: ['childern', 'childran'], blank: { at: 1, options: ['dern', 'dran'] } },
      { word: 'family', sentence: 'My family eats dinner at six.', chunks: ['fam', 'i', 'ly'], distractors: ['familly', 'famly'], blank: { at: 1, options: ['e', 'a'] } },
      { word: 'birthday', sentence: 'Her birthday is in October.', chunks: ['birth', 'day'], distractors: ['brithday', 'birhtday'], blank: { at: 0, options: ['berth', 'burth'] } },
      { word: 'always', sentence: 'He always ties his shoes first.', chunks: ['al', 'ways'], distractors: ['allways', 'alwayz'], blank: { at: 0, options: ['all', 'ol'] } },
      { word: 'another', sentence: 'Can I have another turn?', chunks: ['an', 'oth', 'er'], distractors: ['anouther', 'annother'], blank: { at: 1, options: ['uth', 'ath'] } },
      { word: 'something', sentence: 'I heard something outside.', chunks: ['some', 'thing'], distractors: ['somthing', 'someting'], blank: { at: 0, options: ['sum', 'som'] } },
      { word: 'anything', sentence: 'You can build anything with blocks.', chunks: ['any', 'thing'], distractors: ['enything', 'anithing'], blank: { at: 0, options: ['eny', 'ani'] } },
      { word: 'around', sentence: 'We walked around the pond.', chunks: ['a', 'round'], distractors: ['arownd', 'aroud'], blank: { at: 1, options: ['rownd', 'roud'] } },
      { word: 'between', sentence: 'Sit between your two classmates.', chunks: ['be', 'tween'], distractors: ['betwen', 'betwean'], blank: { at: 1, options: ['twen', 'twean'] } },
      { word: 'brother', sentence: 'My brother lost a tooth.', chunks: ['broth', 'er'], distractors: ['bruther', 'brothur'], blank: { at: 0, options: ['bruth', 'brothe'] } },
      { word: 'sister', sentence: 'My sister plays the flute.', chunks: ['sis', 'ter'], distractors: ['sistur', 'sistter'], blank: { at: 1, options: ['tur', 'tar'] } },
      { word: 'teacher', sentence: 'Our teacher read us a poem.', chunks: ['teach', 'er'], distractors: ['teecher', 'techer'], blank: { at: 0, options: ['teech', 'tech'] } },
      { word: 'picture', sentence: 'She drew a picture of the lake.', chunks: ['pic', 'ture'], distractors: ['pitcher', 'picure'], blank: { at: 1, options: ['cher', 'chure'] } },
      { word: 'number', sentence: 'Write your lucky number here.', chunks: ['num', 'ber'], distractors: ['numbur', 'nummber'], blank: { at: 1, options: ['bur', 'bar'] } },
      { word: 'finally', sentence: 'We finally reached the top.', chunks: ['fi', 'nal', 'ly'], distractors: ['finaly', 'finelly'], blank: { at: 1, options: ['nel', 'nall'] } },
      { word: 'really', sentence: 'That was really close.', chunks: ['re', 'al', 'ly'], distractors: ['realy', 'reallly'], blank: { at: 2, options: ['y', 'lly'] } },
      { word: 'person', sentence: 'Only one person can go first.', chunks: ['per', 'son'], distractors: ['persen', 'purson'], blank: { at: 0, options: ['pur', 'par'] } },
      { word: 'window', sentence: 'Rain tapped on the window.', chunks: ['win', 'dow'], distractors: ['windo', 'winddow'], blank: { at: 1, options: ['doe', 'dou'] } },
      { word: 'summer', sentence: 'We swim all summer long.', chunks: ['sum', 'mer'], distractors: ['sumer', 'summur'], blank: { at: 1, options: ['mur', 'mar'] } },
      { word: 'winter', sentence: 'The winter wind was sharp.', chunks: ['win', 'ter'], distractors: ['wintur', 'winnter'], blank: { at: 1, options: ['tur', 'tar'] } },
    ],
  },
  {
    id: 'explorer',
    label: 'Explorer Creek',
    grades: 'Grades 3–4',
    description: 'Vowels, endings, and longer words',
    color: '#428fa4',
    icon: '🛶',
    words: [
      { word: 'different', sentence: 'Each snowflake looks different.', chunks: ['dif', 'fer', 'ent'], distractors: ['diffrent', 'differant'], blank: { at: 1, options: ['fr', 'far'] } },
      { word: 'important', sentence: 'Practice is important when learning.', chunks: ['im', 'por', 'tant'], distractors: ['importent', 'inportant'], blank: { at: 2, options: ['tent', 'tint'] } },
      { word: 'favorite', sentence: 'Blue is my favorite color.', chunks: ['fa', 'vor', 'ite'], distractors: ['faverite', 'favorit'], blank: { at: 1, options: ['ver', 'vour'] } },
      { word: 'beautiful', sentence: 'The sunset was beautiful.', chunks: ['beau', 'ti', 'ful'], distractors: ['beautifull', 'butiful'], blank: { at: 0, options: ['bue', 'bu'] } },
      { word: 'probably', sentence: 'We will probably leave after lunch.', chunks: ['prob', 'a', 'bly'], distractors: ['probly', 'probabaly'], blank: { at: 2, options: ['ble', 'bley'] } },
      { word: 'remember', sentence: 'Remember to bring your jacket.', chunks: ['re', 'mem', 'ber'], distractors: ['remeber', 'remmember'], blank: { at: 1, options: ['mm', 'men'] } },
      { word: 'surprise', sentence: 'The party was a surprise.', chunks: ['sur', 'prise'], distractors: ['suprise', 'surprize'], blank: { at: 0, options: ['su', 'ser'] } },
      { word: 'calendar', sentence: 'Mark the date on the calendar.', chunks: ['cal', 'en', 'dar'], distractors: ['calender', 'calandar'], blank: { at: 2, options: ['der', 'dor'] } },
      { word: 'neighbor', sentence: 'Our neighbor has a bright red door.', chunks: ['neigh', 'bor'], distractors: ['nieghbor', 'naybor'], blank: { at: 0, options: ['nigh', 'neig'] } },
      { word: 'question', sentence: 'I raised my hand to ask a question.', chunks: ['ques', 'tion'], distractors: ['queston', 'questoin'], blank: { at: 1, options: ['shun', 'sion'] } },
      { word: 'straight', sentence: 'Draw a straight line down the page.', chunks: ['str', 'aight'], distractors: ['strait', 'strate'], blank: { at: 1, options: ['ait', 'aght'] } },
      { word: 'believe', sentence: 'I believe you can do this.', chunks: ['be', 'lieve'], distractors: ['beleive', 'beleve'], blank: { at: 1, options: ['leive', 'leave'] } },
      { word: 'february', sentence: 'February is the shortest month.', chunks: ['feb', 'ru', 'ary'], distractors: ['febuary', 'februrary'], blank: { at: 1, options: ['u', 'ra'] } },
      { word: 'exercise', sentence: 'We exercise before the game starts.', chunks: ['ex', 'er', 'cise'], distractors: ['excercise', 'exersize'], blank: { at: 2, options: ['size', 'sise'] } },
      { word: 'treasure', sentence: 'The map led us to buried treasure.', chunks: ['trea', 'sure'], distractors: ['treshure', 'treasre'], blank: { at: 0, options: ['tre', 'trae'] } },
      { word: 'wonderful', sentence: 'That was a wonderful story.', chunks: ['won', 'der', 'ful'], distractors: ['wonderfull', 'wunderful'], blank: { at: 2, options: ['full', 'fal'] } },
      { word: 'dangerous', sentence: 'That cliff looks dangerous.', chunks: ['dan', 'ger', 'ous'], distractors: ['dangerus', 'daingerous'], blank: { at: 2, options: ['us', 'ious'] } },
      { word: 'delicious', sentence: 'The soup smelled delicious.', chunks: ['de', 'li', 'cious'], distractors: ['delicous', 'dilicious'], blank: { at: 2, options: ['shus', 'tious'] } },
      { word: 'describe', sentence: 'Can you describe the bird?', chunks: ['de', 'scribe'], distractors: ['discribe', 'describ'], blank: { at: 0, options: ['di', 'da'] } },
      { word: 'imagine', sentence: 'Imagine a city under the sea.', chunks: ['i', 'mag', 'ine'], distractors: ['immagine', 'imagin'], blank: { at: 1, options: ['meg', 'mig'] } },
      { word: 'machine', sentence: 'The machine hummed softly.', chunks: ['ma', 'chine'], distractors: ['mashine', 'machin'], blank: { at: 1, options: ['shine', 'chin'] } },
      { word: 'minute', sentence: 'Wait one minute, please.', chunks: ['min', 'ute'], distractors: ['minit', 'minutte'], blank: { at: 1, options: ['it', 'oot'] } },
      { word: 'natural', sentence: 'The cave is a natural shelter.', chunks: ['nat', 'u', 'ral'], distractors: ['naturel', 'nattural'], blank: { at: 2, options: ['rel', 'rul'] } },
      { word: 'ocean', sentence: 'The ocean was calm today.', chunks: ['o', 'cean'], distractors: ['ocian', 'oshean'], blank: { at: 1, options: ['shun', 'cian'] } },
      { word: 'often', sentence: 'We often hike on Sundays.', chunks: ['of', 'ten'], distractors: ['offen', 'oftin'], blank: { at: 1, options: ['tin', 'tan'] } },
      { word: 'quiet', sentence: 'The reading room stayed quiet.', chunks: ['qui', 'et'], distractors: ['quite', 'quiat'], blank: { at: 0, options: ['que', 'qwi'] } },
      { word: 'special', sentence: 'Today is a special day.', chunks: ['spe', 'cial'], distractors: ['speshal', 'specail'], blank: { at: 1, options: ['shal', 'tial'] } },
      { word: 'stomach', sentence: 'My stomach growled loudly.', chunks: ['stom', 'ach'], distractors: ['stomache', 'stumach'], blank: { at: 1, options: ['ack', 'atch'] } },
      { word: 'terrible', sentence: 'That was a terrible storm.', chunks: ['ter', 'ri', 'ble'], distractors: ['terrable', 'terible'], blank: { at: 1, options: ['ra', 're'] } },
      { word: 'tomorrow', sentence: 'We leave tomorrow at dawn.', chunks: ['to', 'mor', 'row'], distractors: ['tommorow', 'tomorow'], blank: { at: 1, options: ['morr', 'mo'] } },
      { word: 'usually', sentence: 'I usually wake up early.', chunks: ['u', 'su', 'al', 'ly'], distractors: ['usualy', 'usally'], blank: { at: 2, options: ['el', 'ual'] } },
      { word: 'weather', sentence: 'The weather turned cold.', chunks: ['weath', 'er'], distractors: ['wether', 'wheather'], blank: { at: 0, options: ['weth', 'wheath'] } },
    ],
  },
  {
    id: 'trailblazer',
    label: 'Trailblazer Ridge',
    grades: 'Grades 4–5',
    description: 'Tricky roots and letter patterns',
    color: '#e28b4a',
    icon: '⛰️',
    words: [
      { word: 'necessary', sentence: 'Water is necessary on a long hike.', chunks: ['nec', 'es', 'sar', 'y'], distractors: ['neccessary', 'necessery'], blank: { at: 2, options: ['ser', 'sarr'] } },
      { word: 'separate', sentence: 'Put the papers in separate piles.', chunks: ['sep', 'a', 'rate'], distractors: ['seperate', 'seperrate'], blank: { at: 1, options: ['e', 'o'] } },
      { word: 'environment', sentence: 'We can help protect the environment.', chunks: ['en', 'vi', 'ron', 'ment'], distractors: ['enviroment', 'environmant'], blank: { at: 2, options: ['ren', 'rn'] } },
      { word: 'knowledge', sentence: 'Reading builds knowledge.', chunks: ['know', 'ledge'], distractors: ['knowlege', 'nolidge'], blank: { at: 1, options: ['lege', 'lidge'] } },
      { word: 'temperature', sentence: 'The temperature dropped overnight.', chunks: ['tem', 'per', 'a', 'ture'], distractors: ['temprature', 'tempereture'], blank: { at: 3, options: ['chure', 'tur'] } },
      { word: 'especially', sentence: 'I like fruit, especially peaches.', chunks: ['es', 'pe', 'cial', 'ly'], distractors: ['expecially', 'especialy'], blank: { at: 2, options: ['tial', 'sial'] } },
      { word: 'opportunity', sentence: 'The club gave me an opportunity to lead.', chunks: ['op', 'por', 'tu', 'ni', 'ty'], distractors: ['oportunity', 'oppertunity'], blank: { at: 0, options: ['opp', 'ap'] } },
      { word: 'immediately', sentence: 'We left immediately after the bell.', chunks: ['im', 'me', 'di', 'ate', 'ly'], distractors: ['imediately', 'immediatly'], blank: { at: 3, options: ['at', 'iate'] } },
      { word: 'definitely', sentence: 'I will definitely finish the chapter.', chunks: ['def', 'i', 'nite', 'ly'], distractors: ['definately', 'definatly'], blank: { at: 1, options: ['a', 'e'] } },
      { word: 'government', sentence: 'The government meets in that building.', chunks: ['gov', 'ern', 'ment'], distractors: ['goverment', 'govenment'], blank: { at: 1, options: ['ren', 'en'] } },
      { word: 'restaurant', sentence: 'We ate at a new restaurant.', chunks: ['res', 'tau', 'rant'], distractors: ['resturant', 'restraunt'], blank: { at: 1, options: ['tu', 'ta'] } },
      { word: 'business', sentence: 'My aunt runs a small business.', chunks: ['busi', 'ness'], distractors: ['buisness', 'bussiness'], blank: { at: 0, options: ['bisi', 'buis'] } },
      { word: 'beginning', sentence: 'The beginning of the book was slow.', chunks: ['be', 'gin', 'ning'], distractors: ['begining', 'beggining'], blank: { at: 2, options: ['ing', 'nning'] } },
      { word: 'familiar', sentence: 'That song sounds familiar.', chunks: ['fa', 'mil', 'iar'], distractors: ['familar', 'familier'], blank: { at: 2, options: ['ier', 'air'] } },
      { word: 'sincerely', sentence: 'I sincerely hope you win.', chunks: ['sin', 'cere', 'ly'], distractors: ['sincerly', 'sincerley'], blank: { at: 1, options: ['sere', 'ceer'] } },
      { word: 'library', sentence: 'The library is open until six.', chunks: ['li', 'brar', 'y'], distractors: ['libary', 'libraray'], blank: { at: 1, options: ['bary', 'brer'] } },
      { word: 'although', sentence: 'Although it rained, we hiked on.', chunks: ['al', 'though'], distractors: ['allthough', 'althogh'], blank: { at: 1, options: ['thogh', 'tho'] } },
      { word: 'argument', sentence: 'They settled the argument calmly.', chunks: ['ar', 'gu', 'ment'], distractors: ['arguement', 'argumant'], blank: { at: 1, options: ['gue', 'ga'] } },
      { word: 'attention', sentence: 'Please pay attention to the map.', chunks: ['at', 'ten', 'tion'], distractors: ['attension', 'atention'], blank: { at: 2, options: ['sion', 'shun'] } },
      { word: 'certainly', sentence: 'I will certainly be at the gate.', chunks: ['cer', 'tain', 'ly'], distractors: ['certinly', 'certainley'], blank: { at: 1, options: ['ten', 'tian'] } },
      { word: 'character', sentence: 'My favorite character is the fox.', chunks: ['char', 'ac', 'ter'], distractors: ['caracter', 'charactor'], blank: { at: 0, options: ['car', 'chair'] } },
      { word: 'comfortable', sentence: 'These boots are comfortable.', chunks: ['com', 'fort', 'a', 'ble'], distractors: ['comfterble', 'comfortible'], blank: { at: 3, options: ['bel', 'bal'] } },
      { word: 'difficult', sentence: 'The last puzzle was difficult.', chunks: ['dif', 'fi', 'cult'], distractors: ['dificult', 'difficualt'], blank: { at: 1, options: ['fe', 'fu'] } },
      { word: 'experience', sentence: 'Camping was a new experience.', chunks: ['ex', 'pe', 'ri', 'ence'], distractors: ['experiance', 'expierence'], blank: { at: 3, options: ['ance', 'ense'] } },
      { word: 'grateful', sentence: 'I am grateful for your help.', chunks: ['grate', 'ful'], distractors: ['greatful', 'gratefull'], blank: { at: 0, options: ['great', 'grat'] } },
      { word: 'happened', sentence: 'Tell me exactly what happened.', chunks: ['hap', 'pened'], distractors: ['happend', 'hapened'], blank: { at: 1, options: ['pend', 'panned'] } },
      { word: 'interesting', sentence: 'That was an interesting fact.', chunks: ['in', 'ter', 'est', 'ing'], distractors: ['intresting', 'interresting'], blank: { at: 1, options: ['tre', 'tur'] } },
      { word: 'language', sentence: 'She is learning a new language.', chunks: ['lan', 'guage'], distractors: ['langauge', 'languge'], blank: { at: 1, options: ['gauge', 'guge'] } },
      { word: 'medicine', sentence: 'The medicine tasted bitter.', chunks: ['med', 'i', 'cine'], distractors: ['medecine', 'medicin'], blank: { at: 1, options: ['a', 'e'] } },
      { word: 'quarter', sentence: 'A quarter of the pie is left.', chunks: ['quar', 'ter'], distractors: ['quater', 'quartar'], blank: { at: 0, options: ['qua', 'quor'] } },
      { word: 'reference', sentence: 'Use the atlas as a reference.', chunks: ['ref', 'er', 'ence'], distractors: ['referrence', 'referance'], blank: { at: 2, options: ['ance', 'ense'] } },
      { word: 'schedule', sentence: 'Check the schedule for the bus.', chunks: ['sched', 'ule'], distractors: ['schedual', 'shedule'], blank: { at: 0, options: ['shed', 'sked'] } },
    ],
  },
  {
    id: 'summit',
    label: 'Summit Challenge',
    grades: 'Grades 5–6',
    description: 'Advanced words for confident climbers',
    color: '#8d6aae',
    icon: '🏔️',
    words: [
      { word: 'accommodate', sentence: 'The room can accommodate twelve people.', chunks: ['ac', 'com', 'mo', 'date'], distractors: ['acommodate', 'accomodate'], blank: { at: 1, options: ['co', 'comm'] } },
      { word: 'conscience', sentence: 'My conscience told me to be honest.', chunks: ['con', 'science'], distractors: ['concience', 'consciense'], blank: { at: 1, options: ['sience', 'scence'] } },
      { word: 'embarrass', sentence: 'A small mistake does not have to embarrass you.', chunks: ['em', 'bar', 'rass'], distractors: ['embarass', 'embarras'], blank: { at: 2, options: ['ras', 'rasse'] } },
      { word: 'rhythm', sentence: 'The drummer kept a steady rhythm.', chunks: ['rhy', 'thm'], distractors: ['rythm', 'rhythum'], blank: { at: 0, options: ['ry', 'rhi'] } },
      { word: 'privilege', sentence: 'It is a privilege to join the team.', chunks: ['priv', 'i', 'lege'], distractors: ['privelege', 'priviledge'], blank: { at: 2, options: ['ledge', 'lige'] } },
      { word: 'recommend', sentence: 'I recommend this mystery book.', chunks: ['rec', 'om', 'mend'], distractors: ['reccomend', 'recomend'], blank: { at: 1, options: ['omm', 'o'] } },
      { word: 'occasionally', sentence: 'We occasionally eat breakfast outside.', chunks: ['oc', 'ca', 'sion', 'al', 'ly'], distractors: ['ocassionally', 'occasionaly'], blank: { at: 2, options: ['tion', 'shion'] } },
      { word: 'pronunciation', sentence: 'The dictionary shows the pronunciation.', chunks: ['pro', 'nun', 'ci', 'a', 'tion'], distractors: ['pronounciation', 'pronuncation'], blank: { at: 1, options: ['noun', 'nunn'] } },
      { word: 'maintenance', sentence: 'The bridge is closed for maintenance.', chunks: ['main', 'te', 'nance'], distractors: ['maintanance', 'maintenence'], blank: { at: 1, options: ['ta', 'ti'] } },
      { word: 'questionnaire', sentence: 'Please fill out the questionnaire.', chunks: ['ques', 'tion', 'naire'], distractors: ['questionaire', 'questionnare'], blank: { at: 2, options: ['nare', 'nair'] } },
      { word: 'independent', sentence: 'She is an independent reader now.', chunks: ['in', 'de', 'pend', 'ent'], distractors: ['independant', 'indepindent'], blank: { at: 3, options: ['ant', 'int'] } },
      { word: 'achievement', sentence: 'Finishing the race was an achievement.', chunks: ['a', 'chieve', 'ment'], distractors: ['acheivement', 'achievment'], blank: { at: 1, options: ['cheive', 'chive'] } },
      { word: 'guarantee', sentence: 'I cannot guarantee the weather.', chunks: ['guar', 'an', 'tee'], distractors: ['garantee', 'guarentee'], blank: { at: 0, options: ['gar', 'guer'] } },
      { word: 'parallel', sentence: 'The two trails run parallel for a mile.', chunks: ['par', 'al', 'lel'], distractors: ['paralell', 'parralel'], blank: { at: 2, options: ['lell', 'llel'] } },
      { word: 'vacuum', sentence: 'Please vacuum the rug before dinner.', chunks: ['vac', 'uum'], distractors: ['vaccum', 'vacume'], blank: { at: 1, options: ['um', 'uom'] } },
      { word: 'exaggerate', sentence: 'Try not to exaggerate the story.', chunks: ['ex', 'ag', 'ger', 'ate'], distractors: ['exagerate', 'exaggarate'], blank: { at: 1, options: ['agg', 'a'] } },
      { word: 'acknowledge', sentence: 'Please acknowledge the message.', chunks: ['ac', 'knowl', 'edge'], distractors: ['aknowledge', 'acknowlege'], blank: { at: 1, options: ['nowl', 'knowel'] } },
      { word: 'apparent', sentence: 'The problem became apparent quickly.', chunks: ['ap', 'par', 'ent'], distractors: ['aparent', 'apparant'], blank: { at: 2, options: ['ant', 'int'] } },
      { word: 'category', sentence: 'Pick a category for your report.', chunks: ['cat', 'e', 'go', 'ry'], distractors: ['catagory', 'cathegory'], blank: { at: 1, options: ['a', 'i'] } },
      { word: 'cemetery', sentence: 'The old cemetery sits on the hill.', chunks: ['cem', 'e', 'ter', 'y'], distractors: ['cemetary', 'cemetry'], blank: { at: 2, options: ['tar', 'tery'] } },
      { word: 'committee', sentence: 'The committee met on Friday.', chunks: ['com', 'mit', 'tee'], distractors: ['commitee', 'comittee'], blank: { at: 2, options: ['te', 'ttee'] } },
      { word: 'curiosity', sentence: 'Her curiosity led to a discovery.', chunks: ['cu', 'ri', 'os', 'ity'], distractors: ['curiousity', 'curiosety'], blank: { at: 2, options: ['ous', 'us'] } },
      { word: 'desperate', sentence: 'We were desperate for shade.', chunks: ['des', 'per', 'ate'], distractors: ['desparate', 'desprate'], blank: { at: 1, options: ['par', 'pir'] } },
      { word: 'existence', sentence: 'No one knew of its existence.', chunks: ['ex', 'ist', 'ence'], distractors: ['existance', 'existense'], blank: { at: 2, options: ['ance', 'ense'] } },
      { word: 'foreign', sentence: 'He studied a foreign alphabet.', chunks: ['for', 'eign'], distractors: ['foriegn', 'forign'], blank: { at: 1, options: ['ien', 'iegn'] } },
      { word: 'gauge', sentence: 'Check the fuel gauge before driving.', chunks: ['gau', 'ge'], distractors: ['guage', 'gage'], blank: { at: 0, options: ['gua', 'ga'] } },
      { word: 'humorous', sentence: 'The story was humorous.', chunks: ['hu', 'mor', 'ous'], distractors: ['humourous', 'humerous'], blank: { at: 1, options: ['mer', 'mour'] } },
      { word: 'jewelry', sentence: 'She kept her jewelry in a tin.', chunks: ['jew', 'el', 'ry'], distractors: ['jewlery', 'jewelery'], blank: { at: 1, options: ['le', 'al'] } },
      { word: 'leisure', sentence: 'We read at leisure on Sundays.', chunks: ['lei', 'sure'], distractors: ['liesure', 'leasure'], blank: { at: 0, options: ['lie', 'lea'] } },
      { word: 'noticeable', sentence: 'The change was noticeable.', chunks: ['no', 'tice', 'a', 'ble'], distractors: ['noticable', 'noticeble'], blank: { at: 2, options: ['e', 'i'] } },
      { word: 'persuade', sentence: 'Try to persuade the group.', chunks: ['per', 'suade'], distractors: ['pursuade', 'perswade'], blank: { at: 1, options: ['swade', 'suede'] } },
      { word: 'relevant', sentence: 'Only relevant facts belong here.', chunks: ['rel', 'e', 'vant'], distractors: ['relevent', 'revelant'], blank: { at: 2, options: ['vent', 'vint'] } },
    ],
  },
  {
    id: 'expedition',
    label: 'Expedition Peak',
    grades: 'Grades 7–8',
    description: 'Long words that trip up grown-ups too',
    color: '#3f7f8c',
    icon: '🧗',
    words: [
      { word: 'conscientious', sentence: 'She is a conscientious note taker.', chunks: ['con', 'sci', 'en', 'tious'], distractors: ['consciencious', 'conscientous'], blank: { at: 3, options: ['cious', 'tous'] } },
      { word: 'entrepreneur', sentence: 'The entrepreneur opened a bakery.', chunks: ['en', 'tre', 'pre', 'neur'], distractors: ['entreprenur', 'entrepeneur'], blank: { at: 3, options: ['nuer', 'nour'] } },
      { word: 'millennium', sentence: 'The castle stood for a millennium.', chunks: ['mil', 'len', 'ni', 'um'], distractors: ['milennium', 'millenium'], blank: { at: 1, options: ['lenn', 'le'] } },
      { word: 'perseverance', sentence: 'Her perseverance paid off at last.', chunks: ['per', 'se', 'ver', 'ance'], distractors: ['perseverence', 'persaverance'], blank: { at: 3, options: ['ence', 'anse'] } },
      { word: 'acquaintance', sentence: 'He is an acquaintance from camp.', chunks: ['ac', 'quain', 'tance'], distractors: ['aquaintance', 'acquaintence'], blank: { at: 1, options: ['quan', 'quian'] } },
      { word: 'bureaucracy', sentence: 'The permit was lost in bureaucracy.', chunks: ['bu', 'reau', 'cra', 'cy'], distractors: ['beaurocracy', 'bureacracy'], blank: { at: 1, options: ['rau', 'reo'] } },
      { word: 'hierarchy', sentence: 'The team has a clear hierarchy.', chunks: ['hi', 'er', 'ar', 'chy'], distractors: ['heirarchy', 'hierarcy'], blank: { at: 3, options: ['cy', 'key'] } },
      { word: 'inevitable', sentence: 'Rain on the trip felt inevitable.', chunks: ['in', 'ev', 'i', 'table'], distractors: ['inevitible', 'inevatable'], blank: { at: 3, options: ['tible', 'tabel'] } },
      { word: 'liaison', sentence: 'She acts as the liaison between classes.', chunks: ['li', 'ai', 'son'], distractors: ['liason', 'liasion'], blank: { at: 1, options: ['a', 'ia'] } },
      { word: 'miscellaneous', sentence: 'The drawer holds miscellaneous tools.', chunks: ['mis', 'cel', 'la', 'neous'], distractors: ['miscelaneous', 'miscellanious'], blank: { at: 3, options: ['nious', 'neus'] } },
      { word: 'occurrence', sentence: 'A blue moon is a rare occurrence.', chunks: ['oc', 'cur', 'rence'], distractors: ['occurence', 'ocurrence'], blank: { at: 2, options: ['ence', 'rance'] } },
      { word: 'pharaoh', sentence: 'The pharaoh ruled for forty years.', chunks: ['phar', 'aoh'], distractors: ['pharoah', 'faraoh'], blank: { at: 1, options: ['oah', 'aho'] } },
      { word: 'rendezvous', sentence: 'We set a rendezvous at the trailhead.', chunks: ['ren', 'dez', 'vous'], distractors: ['rendevous', 'rendezvouz'], blank: { at: 2, options: ['voo', 'vus'] } },
      { word: 'silhouette', sentence: 'A silhouette appeared against the sky.', chunks: ['sil', 'hou', 'ette'], distractors: ['sillhouette', 'silouette'], blank: { at: 1, options: ['ho', 'hue'] } },
      { word: 'threshold', sentence: 'She paused at the threshold of the cabin.', chunks: ['thresh', 'old'], distractors: ['threshhold', 'thresold'], blank: { at: 0, options: ['thres', 'thrash'] } },
      { word: 'unanimous', sentence: 'The vote was unanimous.', chunks: ['u', 'nan', 'i', 'mous'], distractors: ['unanamous', 'unaminous'], blank: { at: 3, options: ['mus', 'mious'] } },
      { word: 'accessible', sentence: 'The trail is accessible by bike.', chunks: ['ac', 'ces', 'si', 'ble'], distractors: ['accesible', 'acessible'], blank: { at: 1, options: ['ses', 'cess'] } },
      { word: 'ambiguous', sentence: 'The ending felt ambiguous.', chunks: ['am', 'big', 'u', 'ous'], distractors: ['ambigous', 'ambiguious'], blank: { at: 1, options: ['bigu', 'beg'] } },
      { word: 'camaraderie', sentence: 'The team built real camaraderie.', chunks: ['ca', 'ma', 'ra', 'derie'], distractors: ['comraderie', 'camaradery'], blank: { at: 3, options: ['dery', 'derry'] } },
      { word: 'connoisseur', sentence: 'She is a connoisseur of old maps.', chunks: ['con', 'nois', 'seur'], distractors: ['conoisseur', 'connoiseur'], blank: { at: 2, options: ['sur', 'seaur'] } },
      { word: 'definitive', sentence: 'There is no definitive ruling yet.', chunks: ['de', 'fin', 'i', 'tive'], distractors: ['definative', 'defenitive'], blank: { at: 2, options: ['a', 'e'] } },
      { word: 'exhilarate', sentence: 'Steep descents exhilarate him.', chunks: ['ex', 'hil', 'a', 'rate'], distractors: ['exhilerate', 'exilarate'], blank: { at: 1, options: ['hel', 'hill'] } },
      { word: 'fluorescent', sentence: 'The sign glowed fluorescent green.', chunks: ['fluo', 'res', 'cent'], distractors: ['flourescent', 'fluorescant'], blank: { at: 0, options: ['flou', 'flu'] } },
      { word: 'harass', sentence: 'Do not harass the wildlife.', chunks: ['ha', 'rass'], distractors: ['harrass', 'haras'], blank: { at: 1, options: ['ras', 'rasse'] } },
      { word: 'idiosyncrasy', sentence: 'That habit is a small idiosyncrasy.', chunks: ['id', 'i', 'o', 'syn', 'crasy'], distractors: ['idiosyncracy', 'ideosyncrasy'], blank: { at: 4, options: ['cracy', 'crazy'] } },
      { word: 'indispensable', sentence: 'A compass is indispensable out here.', chunks: ['in', 'dis', 'pen', 'sable'], distractors: ['indispensible', 'indispensabel'], blank: { at: 3, options: ['sible', 'sabel'] } },
      { word: 'maneuver', sentence: 'The pilot made a careful maneuver.', chunks: ['ma', 'neu', 'ver'], distractors: ['manuever', 'maneuvre'], blank: { at: 1, options: ['nue', 'noo'] } },
      { word: 'plagiarism', sentence: 'Citing sources prevents plagiarism.', chunks: ['pla', 'gia', 'rism'], distractors: ['plagerism', 'plagarism'], blank: { at: 1, options: ['ger', 'gar'] } },
      { word: 'reminiscent', sentence: 'The smell was reminiscent of pine.', chunks: ['rem', 'i', 'nis', 'cent'], distractors: ['reminicent', 'reminescent'], blank: { at: 3, options: ['sent', 'scent'] } },
      { word: 'supersede', sentence: 'New rules supersede the old ones.', chunks: ['su', 'per', 'sede'], distractors: ['supercede', 'superseed'], blank: { at: 2, options: ['cede', 'seed'] } },
      { word: 'vacillate', sentence: 'Do not vacillate at the summit.', chunks: ['vac', 'il', 'late'], distractors: ['vasillate', 'vacilate'], blank: { at: 1, options: ['ill', 'el'] } },
      { word: 'weird', sentence: 'That cloud has a weird shape.', chunks: ['we', 'ird'], distractors: ['wierd', 'weerd'], blank: { at: 1, options: ['ierd', 'eird'] } },
    ],
  },
]

export const DEFAULT_TIER_ID = 'warmup'
